//****************************************************************************//
// Verilog models generated by SiliconSmart P-2019.06-2 build date: Jul 18, 2019 14:03:53. (SMSC-2) //
// Siliconsmart Path: /apps/snps/SiliconSmart-2019.06-2/siliconsmart/P-2019.06-2/linux64/bin/siliconsmart //
// Host Name: edas15fc.corp.towersemi.com, User Name: avipa, PID: 3286        //
// Directory: /direct/sos_proj/ip/NDC/ts18sl_oa_ips/work_libs/avipa/cds/io_conversion/lib_flow_50_scl //
//                                                                            //
// File generated on Wed Mar 01 08:51:13 IST 2023. (SMSC-3)                   //
//****************************************************************************//


`timescale 1ns/1ps

module PAH_18_NA_test_PADR;

  PAH_18_NA instance0(.PAD(PAD), .PADR(PADR));

  PAH_18_NA_stim_PADR instance1(.PAD(PAD), .PADR(PADR));

endmodule

module PAH_18_NA_stim_PADR(PAD, PADR);

  output PAD;
  reg PAD;
  input PADR;

  parameter NUM_INPUT_BITS = 1;
  parameter NUM_OUTPUT_BITS = 1;
  parameter NUM_TOTAL_BITS = NUM_INPUT_BITS + NUM_OUTPUT_BITS;

  parameter OUTPUT_PADR_LOCATION = 1;

  parameter NUM_VECTORS = 8;
  reg [0:NUM_TOTAL_BITS-1] vectors [0:NUM_VECTORS-1];
  reg [0:NUM_TOTAL_BITS-1] ivector;
  integer ctr;

  initial begin

    vectors[0] = {1'b0, 1'b0};
    vectors[1] = {1'b1, 1'b1};
    vectors[2] = {1'b1, 1'b1};
    vectors[3] = {1'b0, 1'b0};
    vectors[4] = {1'b0, 1'b0};
    vectors[5] = {1'b1, 1'b1};
    vectors[6] = {1'b1, 1'b1};
    vectors[7] = {1'b0, 1'b0};

    for (ctr=0; ctr < NUM_VECTORS; ctr=ctr+1)
    begin
      ivector = vectors[ctr];
      {PAD} = ivector[0:NUM_INPUT_BITS-1];
      #20;  
      if(ivector[OUTPUT_PADR_LOCATION] !== PADR && ivector[OUTPUT_PADR_LOCATION] !== 1'bx)
        $display("testbench ERROR : PAH_18_NA:PADR output mismatch at vector no. %d, expected %b != observed %b",
                 ctr, ivector[OUTPUT_PADR_LOCATION], PADR);
    end

  end

endmodule

module PAL_NA_18_test_PADR;

  PAL_NA_18 instance0(.PAD(PAD), .PADR(PADR));

  PAL_NA_18_stim_PADR instance1(.PAD(PAD), .PADR(PADR));

endmodule

module PAL_NA_18_stim_PADR(PAD, PADR);

  output PAD;
  reg PAD;
  input PADR;

  parameter NUM_INPUT_BITS = 1;
  parameter NUM_OUTPUT_BITS = 1;
  parameter NUM_TOTAL_BITS = NUM_INPUT_BITS + NUM_OUTPUT_BITS;

  parameter OUTPUT_PADR_LOCATION = 1;

  parameter NUM_VECTORS = 8;
  reg [0:NUM_TOTAL_BITS-1] vectors [0:NUM_VECTORS-1];
  reg [0:NUM_TOTAL_BITS-1] ivector;
  integer ctr;

  initial begin

    vectors[0] = {1'b0, 1'b0};
    vectors[1] = {1'b1, 1'b1};
    vectors[2] = {1'b1, 1'b1};
    vectors[3] = {1'b0, 1'b0};
    vectors[4] = {1'b0, 1'b0};
    vectors[5] = {1'b1, 1'b1};
    vectors[6] = {1'b1, 1'b1};
    vectors[7] = {1'b0, 1'b0};

    for (ctr=0; ctr < NUM_VECTORS; ctr=ctr+1)
    begin
      ivector = vectors[ctr];
      {PAD} = ivector[0:NUM_INPUT_BITS-1];
      #20;  
      if(ivector[OUTPUT_PADR_LOCATION] !== PADR && ivector[OUTPUT_PADR_LOCATION] !== 1'bx)
        $display("testbench ERROR : PAL_NA_18:PADR output mismatch at vector no. %d, expected %b != observed %b",
                 ctr, ivector[OUTPUT_PADR_LOCATION], PADR);
    end

  end

endmodule

module PIOH_18_18_test_CIN_PAD;

  PIOH_18_18 instance0(.PAD(PAD), .SCHM_ON(SCHM_ON), .EN(EN), .IE(IE), .VDDO_OK(VDDO_OK), .I(I), .PULL_UP_DOWN(PULL_UP_DOWN), .PULL_ON(PULL_ON), .TTL_ON(TTL_ON), .DRIVE_STR(DRIVE_STR), .VDD_OK(VDD_OK), .CIN(CIN));

  PIOH_18_18_stim_CIN_PAD instance1(.PAD(PAD), .SCHM_ON(SCHM_ON), .EN(EN), .IE(IE), .VDDO_OK(VDDO_OK), .I(I), .PULL_UP_DOWN(PULL_UP_DOWN), .PULL_ON(PULL_ON), .TTL_ON(TTL_ON), .DRIVE_STR(DRIVE_STR), .VDD_OK(VDD_OK), .CIN(CIN));

endmodule

module PIOH_18_18_stim_CIN_PAD(PAD, SCHM_ON, EN, IE, VDDO_OK, I, PULL_UP_DOWN, PULL_ON, TTL_ON, DRIVE_STR, VDD_OK, CIN);

  output SCHM_ON;
  reg SCHM_ON;
  output EN;
  reg EN;
  output IE;
  reg IE;
  output VDDO_OK;
  reg VDDO_OK;
  output I;
  reg I;
  output PULL_UP_DOWN;
  reg PULL_UP_DOWN;
  output PULL_ON;
  reg PULL_ON;
  output TTL_ON;
  reg TTL_ON;
  output DRIVE_STR;
  reg DRIVE_STR;
  output VDD_OK;
  reg VDD_OK;
  input CIN;
  inout PAD;
  reg _io_PAD;
  reg _io_ena_PAD;

  parameter NUM_INPUT_BITS = 11;
  parameter NUM_OUTPUT_BITS = 2;
  parameter NUM_TOTAL_BITS = NUM_INPUT_BITS + NUM_OUTPUT_BITS;

  parameter OUTPUT_CIN_LOCATION = 11;
  parameter OUTPUT_PAD_LOCATION = 12;

  parameter NUM_VECTORS = 68;
  reg [0:NUM_TOTAL_BITS-1] vectors [0:NUM_VECTORS-1];
  reg [0:NUM_TOTAL_BITS-1] ivector;
  integer ctr;

  initial begin

    vectors[0] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[1] = {1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[2] = {1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[3] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[4] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[5] = {1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[6] = {1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[7] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[8] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[9] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[10] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[11] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[12] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[13] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[14] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[15] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[16] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[17] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[18] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[19] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[20] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[21] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[22] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[23] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[24] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[25] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[26] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[27] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[28] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'bx, 1'bx};
    vectors[29] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'bx, 1'bx};
    vectors[30] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'bx, 1'bx};
    vectors[31] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'bx, 1'bx};
    vectors[32] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx, 1'bx};
    vectors[33] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'bx, 1'bx};
    vectors[34] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'bx, 1'bx};
    vectors[35] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx, 1'bx};
    vectors[36] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};
    vectors[37] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[38] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[39] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};
    vectors[40] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[41] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[42] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[43] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[44] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[45] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[46] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[47] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[48] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};
    vectors[49] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[50] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[51] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};
    vectors[52] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};
    vectors[53] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[54] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[55] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};
    vectors[56] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[57] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[58] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[59] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[60] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[61] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[62] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b1, 1'bx};
    vectors[63] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'bx};
    vectors[64] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};
    vectors[65] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[66] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b1};
    vectors[67] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0};

    for (ctr=0; ctr < NUM_VECTORS; ctr=ctr+1)
    begin
      ivector = vectors[ctr];
      {DRIVE_STR, EN, I, IE, _io_PAD, PULL_ON, PULL_UP_DOWN, SCHM_ON, TTL_ON, VDDO_OK, VDD_OK} = ivector[0:NUM_INPUT_BITS-1];

      _io_ena_PAD =  (ivector[OUTPUT_PAD_LOCATION] === 1'bx) ? 1'b1 : 1'b0;
      #20;  
      if(ivector[OUTPUT_CIN_LOCATION] !== CIN && ivector[OUTPUT_CIN_LOCATION] !== 1'bx)
        $display("testbench ERROR : PIOH_18_18:CIN output mismatch at vector no. %d, expected %b != observed %b",
                 ctr, ivector[OUTPUT_CIN_LOCATION], CIN);
      if(ivector[OUTPUT_PAD_LOCATION] !== PAD && ivector[OUTPUT_PAD_LOCATION] !== 1'bx)
        $display("testbench ERROR : PIOH_18_18:PAD output mismatch at vector no. %d, expected %b != observed %b",
                 ctr, ivector[OUTPUT_PAD_LOCATION], PAD);
    end

  end

  bufif1(PAD, _io_PAD, _io_ena_PAD);

endmodule

module PIOL_NA_18_test_CIN_PAD;

  PIOL_NA_18 instance0(.PAD(PAD), .PULL_UP_DOWN(PULL_UP_DOWN), .DRIVE_STR(DRIVE_STR), .PULL_ON(PULL_ON), .EN(EN), .IE(IE), .I(I), .SCHM_ON(SCHM_ON), .CIN(CIN));

  PIOL_NA_18_stim_CIN_PAD instance1(.PAD(PAD), .PULL_UP_DOWN(PULL_UP_DOWN), .DRIVE_STR(DRIVE_STR), .PULL_ON(PULL_ON), .EN(EN), .IE(IE), .I(I), .SCHM_ON(SCHM_ON), .CIN(CIN));

endmodule

module PIOL_NA_18_stim_CIN_PAD(PAD, PULL_UP_DOWN, DRIVE_STR, PULL_ON, EN, IE, I, SCHM_ON, CIN);

  output PULL_UP_DOWN;
  reg PULL_UP_DOWN;
  output DRIVE_STR;
  reg DRIVE_STR;
  output PULL_ON;
  reg PULL_ON;
  output EN;
  reg EN;
  output IE;
  reg IE;
  output I;
  reg I;
  output SCHM_ON;
  reg SCHM_ON;
  input CIN;
  inout PAD;
  reg _io_PAD;
  reg _io_ena_PAD;

  parameter NUM_INPUT_BITS = 8;
  parameter NUM_OUTPUT_BITS = 2;
  parameter NUM_TOTAL_BITS = NUM_INPUT_BITS + NUM_OUTPUT_BITS;

  parameter OUTPUT_CIN_LOCATION = 8;
  parameter OUTPUT_PAD_LOCATION = 9;

  parameter NUM_VECTORS = 56;
  reg [0:NUM_TOTAL_BITS-1] vectors [0:NUM_VECTORS-1];
  reg [0:NUM_TOTAL_BITS-1] ivector;
  integer ctr;

  initial begin

    vectors[0] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[1] = {1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[2] = {1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[3] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[4] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[5] = {1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[6] = {1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[7] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[8] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[9] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[10] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[11] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[12] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[13] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[14] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[15] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[16] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[17] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'bx};
    vectors[18] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'bx};
    vectors[19] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[20] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[21] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'bx};
    vectors[22] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'bx};
    vectors[23] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[24] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0};
    vectors[25] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1};
    vectors[26] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1};
    vectors[27] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0};
    vectors[28] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[29] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[30] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[31] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[32] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[33] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[34] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[35] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[36] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0};
    vectors[37] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1};
    vectors[38] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1};
    vectors[39] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0};
    vectors[40] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0};
    vectors[41] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1};
    vectors[42] = {1'b0, 1'b1, 1'b1, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1};
    vectors[43] = {1'b0, 1'b1, 1'b0, 1'b0, 1'bx, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0};
    vectors[44] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[45] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[46] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[47] = {1'b0, 1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[48] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[49] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[50] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b1, 1'b0, 1'b0, 1'b0, 1'b1, 1'bx};
    vectors[51] = {1'b0, 1'b0, 1'b0, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'bx};
    vectors[52] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0};
    vectors[53] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1};
    vectors[54] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b1, 1'b0, 1'b0, 1'b1};
    vectors[55] = {1'b0, 1'b0, 1'b0, 1'b0, 1'bx, 1'b1, 1'b0, 1'b0, 1'b0, 1'b0};

    for (ctr=0; ctr < NUM_VECTORS; ctr=ctr+1)
    begin
      ivector = vectors[ctr];
      {DRIVE_STR, EN, I, IE, _io_PAD, PULL_ON, PULL_UP_DOWN, SCHM_ON} = ivector[0:NUM_INPUT_BITS-1];

      _io_ena_PAD =  (ivector[OUTPUT_PAD_LOCATION] === 1'bx) ? 1'b1 : 1'b0;
      #20;  
      if(ivector[OUTPUT_CIN_LOCATION] !== CIN && ivector[OUTPUT_CIN_LOCATION] !== 1'bx)
        $display("testbench ERROR : PIOL_NA_18:CIN output mismatch at vector no. %d, expected %b != observed %b",
                 ctr, ivector[OUTPUT_CIN_LOCATION], CIN);
      if(ivector[OUTPUT_PAD_LOCATION] !== PAD && ivector[OUTPUT_PAD_LOCATION] !== 1'bx)
        $display("testbench ERROR : PIOL_NA_18:PAD output mismatch at vector no. %d, expected %b != observed %b",
                 ctr, ivector[OUTPUT_PAD_LOCATION], PAD);
    end

  end

  bufif1(PAD, _io_PAD, _io_ena_PAD);

endmodule
