//****************************************************************************//
// Verilog models generated by SiliconSmart P-2019.06-2 build date: Jul 18, 2019 14:03:53. (SMSC-2) //
// Siliconsmart Path: /apps/snps/SiliconSmart-2019.06-2/siliconsmart/P-2019.06-2/linux64/bin/siliconsmart //
// Host Name: edas15fc.corp.towersemi.com, User Name: avipa, PID: 3286        //
// Directory: /direct/sos_proj/ip/NDC/ts18sl_oa_ips/work_libs/avipa/cds/io_conversion/lib_flow_50_scl //
//                                                                            //
// File generated on Wed Mar 01 08:51:13 IST 2023. (SMSC-3)                   //
//****************************************************************************//


`timescale 1ns/1ps



`celldefine
module PAH_18_NA( PAD, PADR );
   input PAD;
   output PADR;

`ifdef FUNCTIONAL  //  functional //
   PAH_18_NA_func PAH_18_NA_behav_inst(.PAD(PAD),.PADR(PADR));
   
`else
   PAH_18_NA_func PAH_18_NA_inst(.PAD(PAD),.PADR(PADR));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      // comb arc PAD --> PADR
      (PAD => PADR) = (0.1,0.1);
      
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PAL_NA_18( PAD, PADR );
   input PAD;
   output PADR;

`ifdef FUNCTIONAL  //  functional //
   PAL_NA_18_func PAL_NA_18_behav_inst(.PAD(PAD),.PADR(PADR));
   
`else
   PAL_NA_18_func PAL_NA_18_inst(.PAD(PAD),.PADR(PADR));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      // comb arc PAD --> PADR
      (PAD => PADR) = (0.1,0.1);
      
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PIOH_18_18( PAD, SCHM_ON, EN, IE, VDDO_OK, I, PULL_UP_DOWN, PULL_ON, TTL_ON, DRIVE_STR, VDD_OK, CIN );
   input DRIVE_STR, EN, I, IE, PULL_ON, PULL_UP_DOWN, SCHM_ON, TTL_ON, VDDO_OK, VDD_OK;
   inout PAD;
   output CIN;

`ifdef FUNCTIONAL  //  functional //
   PIOH_18_18_func PIOH_18_18_behav_inst(.PAD(PAD),.SCHM_ON(SCHM_ON),.EN(EN),.IE(IE),.VDDO_OK(VDDO_OK),.I(I),.PULL_UP_DOWN(PULL_UP_DOWN),.PULL_ON(PULL_ON),.TTL_ON(TTL_ON),.DRIVE_STR(DRIVE_STR),.VDD_OK(VDD_OK),.CIN(CIN));
   
`else
   PIOH_18_18_func PIOH_18_18_inst(.PAD(PAD),.SCHM_ON(SCHM_ON),.EN(EN),.IE(IE),.VDDO_OK(VDDO_OK),.I(I),.PULL_UP_DOWN(PULL_UP_DOWN),.PULL_ON(PULL_ON),.TTL_ON(TTL_ON),.DRIVE_STR(DRIVE_STR),.VDD_OK(VDD_OK),.CIN(CIN));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      // comb arc IE --> CIN
      (IE => CIN) = (0.1,0.1);
      
      if(SCHM_ON===1'b0 && TTL_ON===1'b0)
      // comb arc PAD --> CIN
      (PAD => CIN) = (0.1,0.1);
      
      if(SCHM_ON===1'b0 && TTL_ON===1'b1)
      // comb arc PAD --> CIN
      (PAD => CIN) = (0.1,0.1);
      
      if(SCHM_ON===1'b1 && TTL_ON===1'b0)
      // comb arc PAD --> CIN
      (PAD => CIN) = (0.1,0.1);
      
      if(SCHM_ON===1'b1 && TTL_ON===1'b1)
      // comb arc PAD --> CIN
      (PAD => CIN) = (0.1,0.1);
      
      if(DRIVE_STR===1'b0)
      // comb arc EN --> PAD
      (EN => PAD) = (0.1,0.1);
      
      if(DRIVE_STR===1'b1)
      // comb arc EN --> PAD
      (EN => PAD) = (0.1,0.1);
      
      if(DRIVE_STR===1'b0)
      // comb arc I --> PAD
      (I => PAD) = (0.1,0.1);
      
      if(DRIVE_STR===1'b1)
      // comb arc I --> PAD
      (I => PAD) = (0.1,0.1);
      
      // comb arc PULL_ON --> PAD
      (PULL_ON => PAD) = (0.1,0.1);
      
      // comb arc PULL_UP_DOWN --> PAD
      (PULL_UP_DOWN => PAD) = (0.1,0.1);
      
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PIOL_NA_18( PAD, PULL_UP_DOWN, DRIVE_STR, PULL_ON, EN, IE, I, SCHM_ON, CIN );
   input DRIVE_STR, EN, I, IE, PULL_ON, PULL_UP_DOWN, SCHM_ON;
   inout PAD;
   output CIN;

`ifdef FUNCTIONAL  //  functional //
   PIOL_NA_18_func PIOL_NA_18_behav_inst(.PAD(PAD),.PULL_UP_DOWN(PULL_UP_DOWN),.DRIVE_STR(DRIVE_STR),.PULL_ON(PULL_ON),.EN(EN),.IE(IE),.I(I),.SCHM_ON(SCHM_ON),.CIN(CIN));
   
`else
   PIOL_NA_18_func PIOL_NA_18_inst(.PAD(PAD),.PULL_UP_DOWN(PULL_UP_DOWN),.DRIVE_STR(DRIVE_STR),.PULL_ON(PULL_ON),.EN(EN),.IE(IE),.I(I),.SCHM_ON(SCHM_ON),.CIN(CIN));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      // comb arc IE --> CIN
      (IE => CIN) = (0.1,0.1);
      
      if(SCHM_ON===1'b0)
      // comb arc PAD --> CIN
      (PAD => CIN) = (0.1,0.1);
      
      if(SCHM_ON===1'b1)
      // comb arc PAD --> CIN
      (PAD => CIN) = (0.1,0.1);
      
      if(DRIVE_STR===1'b0)
      // comb arc EN --> PAD
      (EN => PAD) = (0.1,0.1);
      
      if(DRIVE_STR===1'b1)
      // comb arc EN --> PAD
      (EN => PAD) = (0.1,0.1);
      
      if(DRIVE_STR===1'b0)
      // comb arc I --> PAD
      (I => PAD) = (0.1,0.1);
      
      if(DRIVE_STR===1'b1)
      // comb arc I --> PAD
      (I => PAD) = (0.1,0.1);
      
      // comb arc PULL_ON --> PAD
      (PULL_ON => PAD) = (0.1,0.1);
      
      // comb arc PULL_UP_DOWN --> PAD
      (PULL_UP_DOWN => PAD) = (0.1,0.1);
      
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module POK_18_18( VDDO_OK, VDD_OK );
   output VDDO_OK, VDD_OK;

`ifdef FUNCTIONAL  //  functional //
   POK_18_18_func POK_18_18_behav_inst(.VDDO_OK(VDDO_OK),.VDD_OK(VDD_OK));
   
`else
   POK_18_18_func POK_18_18_inst(.VDDO_OK(VDDO_OK),.VDD_OK(VDD_OK));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PV0A_18_18( VSSO );
   output VSSO;

`ifdef FUNCTIONAL  //  functional //
   PV0A_18_18_func PV0A_18_18_behav_inst(.VSSO(VSSO));
   
`else
   PV0A_18_18_func PV0A_18_18_inst(.VSSO(VSSO));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PV0C_18_18_18( VSSC, VDDC );
   output VDDC, VSSC;

`ifdef FUNCTIONAL  //  functional //
   PV0C_18_18_18_func PV0C_18_18_18_behav_inst(.VSSC(VSSC),.VDDC(VDDC));
   
`else
   PV0C_18_18_18_func PV0C_18_18_18_inst(.VSSC(VSSC),.VDDC(VDDC));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PV0F_18_18( VSSO );
   output VSSO;

`ifdef FUNCTIONAL  //  functional //
   PV0F_18_18_func PV0F_18_18_behav_inst(.VSSO(VSSO));
   
`else
   PV0F_18_18_func PV0F_18_18_inst(.VSSO(VSSO));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PV0I_18_18( VSS );
   output VSS;

`ifdef FUNCTIONAL  //  functional //
   PV0I_18_18_func PV0I_18_18_behav_inst(.VSS(VSS));
   
`else
   PV0I_18_18_func PV0I_18_18_inst(.VSS(VSS));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PVDA_18_NA( VDDO );
   output VDDO;

`ifdef FUNCTIONAL  //  functional //
   PVDA_18_NA_func PVDA_18_NA_behav_inst(.VDDO(VDDO));
   
`else
   PVDA_18_NA_func PVDA_18_NA_inst(.VDDO(VDDO));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PVDC_NA_NA_18( VDDC, VSSC );
   output VDDC, VSSC;

`ifdef FUNCTIONAL  //  functional //
   PVDC_NA_NA_18_func PVDC_NA_NA_18_behav_inst(.VDDC(VDDC),.VSSC(VSSC));
   
`else
   PVDC_NA_NA_18_func PVDC_NA_NA_18_inst(.VDDC(VDDC),.VSSC(VSSC));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PVDF_18_18( VDDO );
   output VDDO;

`ifdef FUNCTIONAL  //  functional //
   PVDF_18_18_func PVDF_18_18_behav_inst(.VDDO(VDDO));
   
`else
   PVDF_18_18_func PVDF_18_18_inst(.VDDO(VDDO));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine


`celldefine
module PVDI_NA_18( VDD );
   output VDD;

`ifdef FUNCTIONAL  //  functional //
   PVDI_NA_18_func PVDI_NA_18_behav_inst(.VDD(VDD));
   
`else
   PVDI_NA_18_func PVDI_NA_18_inst(.VDD(VDD));
   
   // spec_gates_begin
   // spec_gates_end
   specify


   // specify_block_begin
      
   // specify_block_end 
   endspecify

`endif 


endmodule
`endcelldefine
