
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point tdi_enable tdi_enable -type PI PI

//output ports
add mapped point TX[59] TX[59] -type PO PO
add mapped point TX[58] TX[58] -type PO PO
add mapped point TX[57] TX[57] -type PO PO
add mapped point TX[56] TX[56] -type PO PO
add mapped point TX[55] TX[55] -type PO PO
add mapped point TX[54] TX[54] -type PO PO
add mapped point TX[53] TX[53] -type PO PO
add mapped point TX[52] TX[52] -type PO PO
add mapped point TX[51] TX[51] -type PO PO
add mapped point TX[50] TX[50] -type PO PO
add mapped point TX[49] TX[49] -type PO PO
add mapped point TX[48] TX[48] -type PO PO
add mapped point TX[47] TX[47] -type PO PO
add mapped point TX[46] TX[46] -type PO PO
add mapped point TX[45] TX[45] -type PO PO
add mapped point TX[44] TX[44] -type PO PO
add mapped point TX[43] TX[43] -type PO PO
add mapped point TX[42] TX[42] -type PO PO
add mapped point TX[41] TX[41] -type PO PO
add mapped point TX[40] TX[40] -type PO PO
add mapped point TX[39] TX[39] -type PO PO
add mapped point TX[38] TX[38] -type PO PO
add mapped point TX[37] TX[37] -type PO PO
add mapped point TX[36] TX[36] -type PO PO
add mapped point TX[35] TX[35] -type PO PO
add mapped point TX[34] TX[34] -type PO PO
add mapped point TX[33] TX[33] -type PO PO
add mapped point TX[32] TX[32] -type PO PO
add mapped point TX[31] TX[31] -type PO PO
add mapped point TX[30] TX[30] -type PO PO
add mapped point TX[29] TX[29] -type PO PO
add mapped point TX[28] TX[28] -type PO PO
add mapped point TX[27] TX[27] -type PO PO
add mapped point TX[26] TX[26] -type PO PO
add mapped point TX[25] TX[25] -type PO PO
add mapped point TX[24] TX[24] -type PO PO
add mapped point TX[23] TX[23] -type PO PO
add mapped point TX[22] TX[22] -type PO PO
add mapped point TX[21] TX[21] -type PO PO
add mapped point TX[20] TX[20] -type PO PO
add mapped point TX[19] TX[19] -type PO PO
add mapped point TX[18] TX[18] -type PO PO
add mapped point TX[17] TX[17] -type PO PO
add mapped point TX[16] TX[16] -type PO PO
add mapped point TX[15] TX[15] -type PO PO
add mapped point TX[14] TX[14] -type PO PO
add mapped point TX[13] TX[13] -type PO PO
add mapped point TX[12] TX[12] -type PO PO
add mapped point TX[11] TX[11] -type PO PO
add mapped point TX[10] TX[10] -type PO PO
add mapped point TX[9] TX[9] -type PO PO
add mapped point TX[8] TX[8] -type PO PO
add mapped point TX[7] TX[7] -type PO PO
add mapped point TX[6] TX[6] -type PO PO
add mapped point TX[5] TX[5] -type PO PO
add mapped point TX[4] TX[4] -type PO PO
add mapped point TX[3] TX[3] -type PO PO
add mapped point TX[2] TX[2] -type PO PO
add mapped point TX[1] TX[1] -type PO PO
add mapped point TX[0] TX[0] -type PO PO
add mapped point RST[59] RST[59] -type PO PO
add mapped point RST[58] RST[58] -type PO PO
add mapped point RST[57] RST[57] -type PO PO
add mapped point RST[56] RST[56] -type PO PO
add mapped point RST[55] RST[55] -type PO PO
add mapped point RST[54] RST[54] -type PO PO
add mapped point RST[53] RST[53] -type PO PO
add mapped point RST[52] RST[52] -type PO PO
add mapped point RST[51] RST[51] -type PO PO
add mapped point RST[50] RST[50] -type PO PO
add mapped point RST[49] RST[49] -type PO PO
add mapped point RST[48] RST[48] -type PO PO
add mapped point RST[47] RST[47] -type PO PO
add mapped point RST[46] RST[46] -type PO PO
add mapped point RST[45] RST[45] -type PO PO
add mapped point RST[44] RST[44] -type PO PO
add mapped point RST[43] RST[43] -type PO PO
add mapped point RST[42] RST[42] -type PO PO
add mapped point RST[41] RST[41] -type PO PO
add mapped point RST[40] RST[40] -type PO PO
add mapped point RST[39] RST[39] -type PO PO
add mapped point RST[38] RST[38] -type PO PO
add mapped point RST[37] RST[37] -type PO PO
add mapped point RST[36] RST[36] -type PO PO
add mapped point RST[35] RST[35] -type PO PO
add mapped point RST[34] RST[34] -type PO PO
add mapped point RST[33] RST[33] -type PO PO
add mapped point RST[32] RST[32] -type PO PO
add mapped point RST[31] RST[31] -type PO PO
add mapped point RST[30] RST[30] -type PO PO
add mapped point RST[29] RST[29] -type PO PO
add mapped point RST[28] RST[28] -type PO PO
add mapped point RST[27] RST[27] -type PO PO
add mapped point RST[26] RST[26] -type PO PO
add mapped point RST[25] RST[25] -type PO PO
add mapped point RST[24] RST[24] -type PO PO
add mapped point RST[23] RST[23] -type PO PO
add mapped point RST[22] RST[22] -type PO PO
add mapped point RST[21] RST[21] -type PO PO
add mapped point RST[20] RST[20] -type PO PO
add mapped point RST[19] RST[19] -type PO PO
add mapped point RST[18] RST[18] -type PO PO
add mapped point RST[17] RST[17] -type PO PO
add mapped point RST[16] RST[16] -type PO PO
add mapped point RST[15] RST[15] -type PO PO
add mapped point RST[14] RST[14] -type PO PO
add mapped point RST[13] RST[13] -type PO PO
add mapped point RST[12] RST[12] -type PO PO
add mapped point RST[11] RST[11] -type PO PO
add mapped point RST[10] RST[10] -type PO PO
add mapped point RST[9] RST[9] -type PO PO
add mapped point RST[8] RST[8] -type PO PO
add mapped point RST[7] RST[7] -type PO PO
add mapped point RST[6] RST[6] -type PO PO
add mapped point RST[5] RST[5] -type PO PO
add mapped point RST[4] RST[4] -type PO PO
add mapped point RST[3] RST[3] -type PO PO
add mapped point RST[2] RST[2] -type PO PO
add mapped point RST[1] RST[1] -type PO PO
add mapped point RST[0] RST[0] -type PO PO
add mapped point SEL[59] SEL[59] -type PO PO
add mapped point SEL[58] SEL[58] -type PO PO
add mapped point SEL[57] SEL[57] -type PO PO
add mapped point SEL[56] SEL[56] -type PO PO
add mapped point SEL[55] SEL[55] -type PO PO
add mapped point SEL[54] SEL[54] -type PO PO
add mapped point SEL[53] SEL[53] -type PO PO
add mapped point SEL[52] SEL[52] -type PO PO
add mapped point SEL[51] SEL[51] -type PO PO
add mapped point SEL[50] SEL[50] -type PO PO
add mapped point SEL[49] SEL[49] -type PO PO
add mapped point SEL[48] SEL[48] -type PO PO
add mapped point SEL[47] SEL[47] -type PO PO
add mapped point SEL[46] SEL[46] -type PO PO
add mapped point SEL[45] SEL[45] -type PO PO
add mapped point SEL[44] SEL[44] -type PO PO
add mapped point SEL[43] SEL[43] -type PO PO
add mapped point SEL[42] SEL[42] -type PO PO
add mapped point SEL[41] SEL[41] -type PO PO
add mapped point SEL[40] SEL[40] -type PO PO
add mapped point SEL[39] SEL[39] -type PO PO
add mapped point SEL[38] SEL[38] -type PO PO
add mapped point SEL[37] SEL[37] -type PO PO
add mapped point SEL[36] SEL[36] -type PO PO
add mapped point SEL[35] SEL[35] -type PO PO
add mapped point SEL[34] SEL[34] -type PO PO
add mapped point SEL[33] SEL[33] -type PO PO
add mapped point SEL[32] SEL[32] -type PO PO
add mapped point SEL[31] SEL[31] -type PO PO
add mapped point SEL[30] SEL[30] -type PO PO
add mapped point SEL[29] SEL[29] -type PO PO
add mapped point SEL[28] SEL[28] -type PO PO
add mapped point SEL[27] SEL[27] -type PO PO
add mapped point SEL[26] SEL[26] -type PO PO
add mapped point SEL[25] SEL[25] -type PO PO
add mapped point SEL[24] SEL[24] -type PO PO
add mapped point SEL[23] SEL[23] -type PO PO
add mapped point SEL[22] SEL[22] -type PO PO
add mapped point SEL[21] SEL[21] -type PO PO
add mapped point SEL[20] SEL[20] -type PO PO
add mapped point SEL[19] SEL[19] -type PO PO
add mapped point SEL[18] SEL[18] -type PO PO
add mapped point SEL[17] SEL[17] -type PO PO
add mapped point SEL[16] SEL[16] -type PO PO
add mapped point SEL[15] SEL[15] -type PO PO
add mapped point SEL[14] SEL[14] -type PO PO
add mapped point SEL[13] SEL[13] -type PO PO
add mapped point SEL[12] SEL[12] -type PO PO
add mapped point SEL[11] SEL[11] -type PO PO
add mapped point SEL[10] SEL[10] -type PO PO
add mapped point SEL[9] SEL[9] -type PO PO
add mapped point SEL[8] SEL[8] -type PO PO
add mapped point SEL[7] SEL[7] -type PO PO
add mapped point SEL[6] SEL[6] -type PO PO
add mapped point SEL[5] SEL[5] -type PO PO
add mapped point SEL[4] SEL[4] -type PO PO
add mapped point SEL[3] SEL[3] -type PO PO
add mapped point SEL[2] SEL[2] -type PO PO
add mapped point SEL[1] SEL[1] -type PO PO
add mapped point SEL[0] SEL[0] -type PO PO
add mapped point line_done line_done -type PO PO
add mapped point frame_done frame_done -type PO PO

//inout ports




//Sequential Pins
add mapped point row_cnt[5]/q row_cnt_reg[5]/Q -type DFF DFF
add mapped point row_cnt[4]/q row_cnt_reg[4]/Q -type DFF DFF
add mapped point row_cnt[3]/q row_cnt_reg[3]/Q -type DFF DFF
add mapped point line_cnt[9]/q line_cnt_reg[9]/Q -type DFF DFF
add mapped point line_cnt[7]/q line_cnt_reg[7]/Q -type DFF DFF
add mapped point line_cnt[8]/q line_cnt_reg[8]/Q -type DFF DFF
add mapped point frame_done/q frame_done_reg/Q -type DFF DFF
add mapped point row_cnt[2]/q row_cnt_reg[2]/Q -type DFF DFF
add mapped point line_cnt[12]/q line_cnt_reg[12]/Q -type DFF DFF
add mapped point row_cnt[1]/q row_cnt_reg[1]/Q -type DFF DFF
add mapped point line_cnt[11]/q line_cnt_reg[11]/Q -type DFF DFF
add mapped point line_cnt[10]/q line_cnt_reg[10]/Q -type DFF DFF
add mapped point SEL[10]/q SEL_reg[10]/Q -type DFF DFF
add mapped point SEL[54]/q SEL_reg[54]/Q -type DFF DFF
add mapped point TX[4]/q TX_reg[4]/Q -type DFF DFF
add mapped point TX[36]/q TX_reg[36]/Q -type DFF DFF
add mapped point RST[52]/q RST_reg[52]/Q -type DFF DFF
add mapped point SEL[12]/q SEL_reg[12]/Q -type DFF DFF
add mapped point SEL[36]/q SEL_reg[36]/Q -type DFF DFF
add mapped point SEL[4]/q SEL_reg[4]/Q -type DFF DFF
add mapped point SEL[8]/q SEL_reg[8]/Q -type DFF DFF
add mapped point SEL[40]/q SEL_reg[40]/Q -type DFF DFF
add mapped point TX[28]/q TX_reg[28]/Q -type DFF DFF
add mapped point SEL[42]/q SEL_reg[42]/Q -type DFF DFF
add mapped point SEL[22]/q SEL_reg[22]/Q -type DFF DFF
add mapped point SEL[6]/q SEL_reg[6]/Q -type DFF DFF
add mapped point TX[58]/q TX_reg[58]/Q -type DFF DFF
add mapped point SEL[14]/q SEL_reg[14]/Q -type DFF DFF
add mapped point SEL[33]/q SEL_reg[33]/Q -type DFF DFF
add mapped point SEL[32]/q SEL_reg[32]/Q -type DFF DFF
add mapped point RST[38]/q RST_reg[38]/Q -type DFF DFF
add mapped point RST[22]/q RST_reg[22]/Q -type DFF DFF
add mapped point SEL[18]/q SEL_reg[18]/Q -type DFF DFF
add mapped point SEL[30]/q SEL_reg[30]/Q -type DFF DFF
add mapped point SEL[44]/q SEL_reg[44]/Q -type DFF DFF
add mapped point SEL[50]/q SEL_reg[50]/Q -type DFF DFF
add mapped point TX[38]/q TX_reg[38]/Q -type DFF DFF
add mapped point RST[34]/q RST_reg[34]/Q -type DFF DFF
add mapped point SEL[28]/q SEL_reg[28]/Q -type DFF DFF
add mapped point SEL[20]/q SEL_reg[20]/Q -type DFF DFF
add mapped point TX[44]/q TX_reg[44]/Q -type DFF DFF
add mapped point SEL[0]/q SEL_reg[0]/Q -type DFF DFF
add mapped point TX[12]/q TX_reg[12]/Q -type DFF DFF
add mapped point TX[18]/q TX_reg[18]/Q -type DFF DFF
add mapped point RST[37]/q RST_reg[37]/Q -type DFF DFF
add mapped point row_cnt[0]/q row_cnt_reg[0]/Q -type DFF DFF
add mapped point line_cnt[6]/q line_cnt_reg[6]/Q -type DFF DFF
add mapped point SEL[57]/q SEL_reg[57]/Q -type DFF DFF
add mapped point SEL[24]/q SEL_reg[24]/Q -type DFF DFF
add mapped point SEL[56]/q SEL_reg[56]/Q -type DFF DFF
add mapped point SEL[46]/q SEL_reg[46]/Q -type DFF DFF
add mapped point TX[26]/q TX_reg[26]/Q -type DFF DFF
add mapped point RST[2]/q RST_reg[2]/Q -type DFF DFF
add mapped point SEL[26]/q SEL_reg[26]/Q -type DFF DFF
add mapped point RST[42]/q RST_reg[42]/Q -type DFF DFF
add mapped point SEL[16]/q SEL_reg[16]/Q -type DFF DFF
add mapped point TX[11]/q TX_reg[11]/Q -type DFF DFF
add mapped point TX[50]/q TX_reg[50]/Q -type DFF DFF
add mapped point RST[20]/q RST_reg[20]/Q -type DFF DFF
add mapped point TX[6]/q TX_reg[6]/Q -type DFF DFF
add mapped point RST[29]/q RST_reg[29]/Q -type DFF DFF
add mapped point TX[45]/q TX_reg[45]/Q -type DFF DFF
add mapped point TX[8]/q TX_reg[8]/Q -type DFF DFF
add mapped point SEL[25]/q SEL_reg[25]/Q -type DFF DFF
add mapped point RST[28]/q RST_reg[28]/Q -type DFF DFF
add mapped point RST[12]/q RST_reg[12]/Q -type DFF DFF
add mapped point TX[55]/q TX_reg[55]/Q -type DFF DFF
add mapped point SEL[45]/q SEL_reg[45]/Q -type DFF DFF
add mapped point TX[29]/q TX_reg[29]/Q -type DFF DFF
add mapped point TX[21]/q TX_reg[21]/Q -type DFF DFF
add mapped point SEL[3]/q SEL_reg[3]/Q -type DFF DFF
add mapped point line_cnt[3]/q line_cnt_reg[3]/Q -type DFF DFF
add mapped point RST[21]/q RST_reg[21]/Q -type DFF DFF
add mapped point RST[50]/q RST_reg[50]/Q -type DFF DFF
add mapped point RST[14]/q RST_reg[14]/Q -type DFF DFF
add mapped point RST[6]/q RST_reg[6]/Q -type DFF DFF
add mapped point RST[53]/q RST_reg[53]/Q -type DFF DFF
add mapped point RST[30]/q RST_reg[30]/Q -type DFF DFF
add mapped point SEL[52]/q SEL_reg[52]/Q -type DFF DFF
add mapped point TX[16]/q TX_reg[16]/Q -type DFF DFF
add mapped point RST[18]/q RST_reg[18]/Q -type DFF DFF
add mapped point RST[15]/q RST_reg[15]/Q -type DFF DFF
add mapped point TX[10]/q TX_reg[10]/Q -type DFF DFF
add mapped point RST[58]/q RST_reg[58]/Q -type DFF DFF
add mapped point SEL[48]/q SEL_reg[48]/Q -type DFF DFF
add mapped point TX[42]/q TX_reg[42]/Q -type DFF DFF
add mapped point SEL[38]/q SEL_reg[38]/Q -type DFF DFF
add mapped point SEL[34]/q SEL_reg[34]/Q -type DFF DFF
add mapped point TX[40]/q TX_reg[40]/Q -type DFF DFF
add mapped point RST[26]/q RST_reg[26]/Q -type DFF DFF
add mapped point TX[48]/q TX_reg[48]/Q -type DFF DFF
add mapped point TX[34]/q TX_reg[34]/Q -type DFF DFF
add mapped point TX[2]/q TX_reg[2]/Q -type DFF DFF
add mapped point TX[30]/q TX_reg[30]/Q -type DFF DFF
add mapped point SEL[2]/q SEL_reg[2]/Q -type DFF DFF
add mapped point RST[44]/q RST_reg[44]/Q -type DFF DFF
add mapped point SEL[29]/q SEL_reg[29]/Q -type DFF DFF
add mapped point SEL[39]/q SEL_reg[39]/Q -type DFF DFF
add mapped point TX[43]/q TX_reg[43]/Q -type DFF DFF
add mapped point SEL[43]/q SEL_reg[43]/Q -type DFF DFF
add mapped point SEL[19]/q SEL_reg[19]/Q -type DFF DFF
add mapped point SEL[49]/q SEL_reg[49]/Q -type DFF DFF
add mapped point SEL[1]/q SEL_reg[1]/Q -type DFF DFF
add mapped point SEL[37]/q SEL_reg[37]/Q -type DFF DFF
add mapped point line_cnt[5]/q line_cnt_reg[5]/Q -type DFF DFF
add mapped point line_cnt[4]/q line_cnt_reg[4]/Q -type DFF DFF
add mapped point SEL[7]/q SEL_reg[7]/Q -type DFF DFF
add mapped point TX[24]/q TX_reg[24]/Q -type DFF DFF
add mapped point SEL[15]/q SEL_reg[15]/Q -type DFF DFF
add mapped point SEL[23]/q SEL_reg[23]/Q -type DFF DFF
add mapped point TX[20]/q TX_reg[20]/Q -type DFF DFF
add mapped point TX[52]/q TX_reg[52]/Q -type DFF DFF
add mapped point RST[5]/q RST_reg[5]/Q -type DFF DFF
add mapped point TX[56]/q TX_reg[56]/Q -type DFF DFF
add mapped point RST[13]/q RST_reg[13]/Q -type DFF DFF
add mapped point RST[45]/q RST_reg[45]/Q -type DFF DFF
add mapped point TX[32]/q TX_reg[32]/Q -type DFF DFF
add mapped point SEL[27]/q SEL_reg[27]/Q -type DFF DFF
add mapped point RST[47]/q RST_reg[47]/Q -type DFF DFF
add mapped point RST[19]/q RST_reg[19]/Q -type DFF DFF
add mapped point RST[3]/q RST_reg[3]/Q -type DFF DFF
add mapped point TX[0]/q TX_reg[0]/Q -type DFF DFF
add mapped point RST[7]/q RST_reg[7]/Q -type DFF DFF
add mapped point SEL[58]/q SEL_reg[58]/Q -type DFF DFF
add mapped point line_done/q line_done_reg/Q -type DFF DFF
add mapped point RST[10]/q RST_reg[10]/Q -type DFF DFF
add mapped point SEL[47]/q SEL_reg[47]/Q -type DFF DFF
add mapped point SEL[53]/q SEL_reg[53]/Q -type DFF DFF
add mapped point SEL[21]/q SEL_reg[21]/Q -type DFF DFF
add mapped point SEL[13]/q SEL_reg[13]/Q -type DFF DFF
add mapped point TX[31]/q TX_reg[31]/Q -type DFF DFF
add mapped point SEL[35]/q SEL_reg[35]/Q -type DFF DFF
add mapped point SEL[51]/q SEL_reg[51]/Q -type DFF DFF
add mapped point SEL[11]/q SEL_reg[11]/Q -type DFF DFF
add mapped point SEL[5]/q SEL_reg[5]/Q -type DFF DFF
add mapped point SEL[17]/q SEL_reg[17]/Q -type DFF DFF
add mapped point TX[53]/q TX_reg[53]/Q -type DFF DFF
add mapped point TX[1]/q TX_reg[1]/Q -type DFF DFF
add mapped point TX[57]/q TX_reg[57]/Q -type DFF DFF
add mapped point TX[33]/q TX_reg[33]/Q -type DFF DFF
add mapped point line_cnt[2]/q line_cnt_reg[2]/Q -type DFF DFF
add mapped point TX[27]/q TX_reg[27]/Q -type DFF DFF
add mapped point TX[35]/q TX_reg[35]/Q -type DFF DFF
add mapped point RST[32]/q RST_reg[32]/Q -type DFF DFF
add mapped point RST[36]/q RST_reg[36]/Q -type DFF DFF
add mapped point RST[56]/q RST_reg[56]/Q -type DFF DFF
add mapped point RST[23]/q RST_reg[23]/Q -type DFF DFF
add mapped point RST[41]/q RST_reg[41]/Q -type DFF DFF
add mapped point RST[1]/q RST_reg[1]/Q -type DFF DFF
add mapped point SEL[9]/q SEL_reg[9]/Q -type DFF DFF
add mapped point RST[46]/q RST_reg[46]/Q -type DFF DFF
add mapped point RST[54]/q RST_reg[54]/Q -type DFF DFF
add mapped point RST[55]/q RST_reg[55]/Q -type DFF DFF
add mapped point RST[40]/q RST_reg[40]/Q -type DFF DFF
add mapped point RST[57]/q RST_reg[57]/Q -type DFF DFF
add mapped point TX[14]/q TX_reg[14]/Q -type DFF DFF
add mapped point RST[11]/q RST_reg[11]/Q -type DFF DFF
add mapped point RST[51]/q RST_reg[51]/Q -type DFF DFF
add mapped point RST[43]/q RST_reg[43]/Q -type DFF DFF
add mapped point RST[35]/q RST_reg[35]/Q -type DFF DFF
add mapped point RST[39]/q RST_reg[39]/Q -type DFF DFF
add mapped point TX[22]/q TX_reg[22]/Q -type DFF DFF
add mapped point TX[54]/q TX_reg[54]/Q -type DFF DFF
add mapped point RST[4]/q RST_reg[4]/Q -type DFF DFF
add mapped point TX[15]/q TX_reg[15]/Q -type DFF DFF
add mapped point RST[24]/q RST_reg[24]/Q -type DFF DFF
add mapped point RST[16]/q RST_reg[16]/Q -type DFF DFF
add mapped point RST[17]/q RST_reg[17]/Q -type DFF DFF
add mapped point RST[49]/q RST_reg[49]/Q -type DFF DFF
add mapped point RST[25]/q RST_reg[25]/Q -type DFF DFF
add mapped point RST[0]/q RST_reg[0]/Q -type DFF DFF
add mapped point RST[59]/q RST_reg[59]/Q -type DFF DFF
add mapped point TX[3]/q TX_reg[3]/Q -type DFF DFF
add mapped point TX[25]/q TX_reg[25]/Q -type DFF DFF
add mapped point TX[41]/q TX_reg[41]/Q -type DFF DFF
add mapped point TX[5]/q TX_reg[5]/Q -type DFF DFF
add mapped point TX[59]/q TX_reg[59]/Q -type DFF DFF
add mapped point TX[51]/q TX_reg[51]/Q -type DFF DFF
add mapped point TX[23]/q TX_reg[23]/Q -type DFF DFF
add mapped point TX[19]/q TX_reg[19]/Q -type DFF DFF
add mapped point TX[39]/q TX_reg[39]/Q -type DFF DFF
add mapped point TX[17]/q TX_reg[17]/Q -type DFF DFF
add mapped point RST[33]/q RST_reg[33]/Q -type DFF DFF
add mapped point TX[49]/q TX_reg[49]/Q -type DFF DFF
add mapped point TX[37]/q TX_reg[37]/Q -type DFF DFF
add mapped point TX[13]/q TX_reg[13]/Q -type DFF DFF
add mapped point TX[47]/q TX_reg[47]/Q -type DFF DFF
add mapped point TX[7]/q TX_reg[7]/Q -type DFF DFF
add mapped point RST[9]/q RST_reg[9]/Q -type DFF DFF
add mapped point SEL[41]/q SEL_reg[41]/Q -type DFF DFF
add mapped point SEL[31]/q SEL_reg[31]/Q -type DFF DFF
add mapped point RST[31]/q RST_reg[31]/Q -type DFF DFF
add mapped point TX[46]/q TX_reg[46]/Q -type DFF DFF
add mapped point SEL[59]/q SEL_reg[59]/Q -type DFF DFF
add mapped point line_cnt[1]/q line_cnt_reg[1]/Q -type DFF DFF
add mapped point SEL[55]/q SEL_reg[55]/Q -type DFF DFF
add mapped point RST[8]/q RST_reg[8]/Q -type DFF DFF
add mapped point RST[27]/q RST_reg[27]/Q -type DFF DFF
add mapped point RST[48]/q RST_reg[48]/Q -type DFF DFF
add mapped point TX[9]/q TX_reg[9]/Q -type DFF DFF
add mapped point line_cnt[0]/q line_cnt_reg[0]/Q -type DFF DFF
add mapped point tdi_en_s/q tdi_en_s_reg/Q -type DFF DFF
add mapped point en_meta/q en_meta_reg/Q -type DFF DFF
add mapped point rst_n_s/q rst_n_s_reg/Q -type DFF DFF
add mapped point rst_meta/q rst_meta_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
