; Technology File tf_4M1L
; Generated on Jan 15 16:09:17 2024
;     with @(#)$CDS: virtuoso version 6.1.8-64b 05/03/2023 09:48 (sjfhw317) $


;********************************
; CONTROLS
;********************************
controls(
 techVersion("1.0")

 techParams(
 ;( parameter           value             )
 ;( ----------          -----             )
  ( gridResolution 	0.005 )
  ( LEFDEF_MANUFACTURINGGRID	0.005 )
  ( _1A            	0.86 )
  ( _1A_5V         	1.3 )
  ( _1A1           	2.1 )
  ( _1A1_5V        	2.5 )
  ( _1B            	1.4 )
  ( _1B_5V         	2.0 )
  ( _1B1           	0.6 )
  ( _1B1_5V        	0.9 )
  ( _1C            	0.43 )
  ( _1C_5V         	0.65 )
  ( _1D            	0.43 )
  ( _1D_5V         	0.65 )
  ( _1E            	0.12 )
  ( _1E_5V         	0.18 )
  ( _1F            	0.12 )
  ( _1F_5V         	0.18 )
  ( _3A            	0.22 )
  ( _3A_5V         	0.6 )
  ( _3B            	0.28 )
  ( _3B_5V         	0.45 )
  ( _3C            	0.28 )
  ( _3C_5V         	0.45 )
  ( _3D            	0.202 )
  ( _3U            	0.36 )
  ( _3U_5V         	0.55 )
  ( _3V            	0.32 )
  ( _3V_5V         	0.6 )
  ( _3W            	0.32 )
  ( _3W_5V         	0.6 )
  ( _3X            	0.0 )
  ( _3Y            	0.176 )
  ( _3Z            	0.42 )
  ( _6A0_18P       	0.18 )
  ( _6A0_33P       	0.3 )
  ( _6A0_5VP       	0.5 )
  ( _6A0_18N       	0.18 )
  ( _6A0_33N       	0.35 )
  ( _6A0_5VN       	0.6 )
  ( _6A1           	0.18 )
  ( _6B0A          	0.25 )
  ( _6B0A1         	0.375 )
  ( _6B1           	0.25 )
  ( _6C            	0.22 )
  ( _6D            	0.32 )
  ( _6E            	0.1 )
  ( _6E_5V         	0.25 )
  ( _6Y            	0.21 )
  ( XN_A           	0.44 )
  ( XN_B           	0.44 )
  ( XN_C           	0.18 )
  ( XN_D           	0.02 )
  ( XN_L           	0.18 )
  ( XN_E           	0.26 )
  ( XN_F           	0.18 )
  ( XN_P           	0.1 )
  ( XN_G           	0.32 )
  ( XN_G1          	0.32 )
  ( XN_H           	0.23 )
  ( XN_K           	0.3844 )
  ( XN_M           	0.0 )
  ( XN_N           	0.0 )
  ( XN_Q           	0.18 )
  ( XN_S           	0.35 )
  ( XN_SA          	0.32 )
  ( _7A            	0.44 )
  ( _7B            	0.44 )
  ( _7C            	0.18 )
  ( _7D            	0.02 )
  ( _7L            	0.18 )
  ( _7E            	0.26 )
  ( _7F            	0.18 )
  ( _7P            	0.1 )
  ( _7G            	0.32 )
  ( _7G1           	0.32 )
  ( _7H            	0.23 )
  ( _7K            	0.3844 )
  ( _7M            	0.0 )
  ( _7N            	0.0 )
  ( _7Q            	0.18 )
  ( _7S            	0.35 )
  ( _7SA           	0.32 )
  ( NS1            	0.43 )
  ( NS2            	0.43 )
  ( NS3            	0.22 )
  ( NS4            	0.22 )
  ( NS5            	0.45 )
  ( NS7            	0.22 )
  ( NS8            	0.22 )
  ( NS9            	0.3 )
  ( NS10           	2.0 )
  ( NS11           	0.22 )
  ( _8A            	0.22 )
  ( _8B            	0.25 )
  ( _8B1           	0.28 )
  ( _8C            	0.1 )
  ( _8D            	0.1 )
  ( _8E2           	0.16 )
  ( _8F            	0.2 )
  ( _8S            	0.12 )
  ( _8U            	0.12 )
  ( _9A            	0.23 )
  ( _9B            	0.23 )
  ( _9B1           	0.6 )
  ( _9C1           	0.005 )
  ( _9C3           	0.06 )
  ( _9D            	0.202 )
  ( _9X            	0.2 )
  ( _10A           	0.26 )
  ( _10B           	0.26 )
  ( _10C1          	0.01 )
  ( _10C3          	0.06 )
  ( _11A           	0.28 )
  ( _11B           	0.28 )
  ( _11B1          	0.6 )
  ( _11C1          	0.01 )
  ( _11C3          	0.06 )
  ( _11D           	0.202 )
  ( _11X           	0.2 )
  ( _12A           	0.26 )
  ( _12B           	0.26 )
  ( _12C1          	0.01 )
  ( _12C3          	0.06 )
  ( _13A           	0.28 )
  ( _13B           	0.28 )
  ( _13B1          	0.6 )
  ( _13C1          	0.01 )
  ( _13C3          	0.06 )
  ( _13D           	0.202 )
  ( _13X           	0.2 )
  ( _14A           	0.26 )
  ( _14B           	0.26 )
  ( _14C1          	0.01 )
  ( _14C3          	0.06 )
  ( _15A           	0.28 )
  ( _15B           	0.28 )
  ( _15B1          	0.6 )
  ( _15C1          	0.01 )
  ( _15C3          	0.06 )
  ( _15D           	0.202 )
  ( _15X           	0.2 )
  ( _16A           	0.26 )
  ( _16B           	0.26 )
  ( _16C1          	0.01 )
  ( _16C3          	0.06 )
  ( _17A           	0.28 )
  ( _17B           	0.28 )
  ( _17B1          	0.6 )
  ( _17C1          	0.01 )
  ( _17C3          	0.06 )
  ( _17D           	0.202 )
  ( _17X           	0.2 )
  ( _18A           	0.36 )
  ( _18B           	0.35 )
  ( _18C1          	0.01 )
  ( _18C3          	0.06 )
  ( _19A           	0.44 )
  ( _19B           	0.46 )
  ( _19B1          	0.6 )
  ( _19C1          	0.09 )
  ( _19D           	0.562 )
  ( _19X           	0.2 )
  ( _24A           	0.32 )
  ( _24B           	0.32 )
  ( _24B_5V        	0.5 )
  ( _24C           	0.4 )
  ( _24D           	0.4 )
  ( _24D_5V        	0.6 )
  ( _24E           	0.88 )
  ( _24F           	0.45 )
  ( _24F_5V        	0.8 )
  ( VNN_W_1        	0.86 )
  ( VNN_S_1        	0.86 )
  ( VNN_W_2        	0.5 )
  ( VNN_W_3        	1.2 )
  ( VNN_E_1        	0.26 )
  ( VNN_D_1        	0.52 )
  ( VNN_D_2        	1.66 )
  ( VNN_X_1        	0.35 )
  ( MR_01          	0.44 )
  ( MR_02          	0.44 )
  ( MR_03          	2.0 )
  ( MR_04          	0.26 )
  ( MR_05          	0.1 )
  ( MR_06          	0.32 )
  ( MR_07          	0.32 )
  ( MR_09          	0.26 )
  ( MR_10          	0.1 )
  ( MR_11          	0.26 )
  ( MR_15          	0.3844 )
  ( MR_16          	0.3 )
  ( MR_18          	0.26 )
  ( NPR_03         	2.0 )
  ( NPR_18         	0.26 )
  ( PPR_03         	2.0 )
  ( PPR_18         	0.26 )
  ( NAR_01         	2.0 )
  ( PAR_01         	2.0 )
  ( NWR_01         	2.1 )
  ( NWR_02         	1.0 )
  ( NWR_03         	0.3 )
  ( NWR_04         	0.3 )
  ( NWR_05         	0.22 )
  ( NWR_06         	0.3 )
  ( NWR_07         	0.4 )
  ( NWR_20         	1.4 )
  ( NWR_27         	1.2 )
  ( MIM_01         	4.0 )
  ( MIM_01_N       	1.6 )
  ( MIM_02         	0.4 )
  ( MIM_03         	0.4 )
  ( MIM_04         	1.2 )
  ( MIM_05         	0.8 )
  ( MIM_06         	0.8 )
  ( MIM_06_N       	0.6 )
  ( MIM_07         	0.24 )
  ( MIM_08         	0.12 )
  ( MIM_09         	0.12 )
  ( MIM_10         	0.4 )
  ( MIM_11         	0.4 )
  ( MIM_12         	0.4 )
  ( MIM_14         	0.03 )
  ( MIM_17         	2.0 )
  ( MIM_18         	0.01 )
  ( MIM_19         	4.0 )
  ( MIM_20         	2.0 )
  ( MIM_21         	2.0 )
  ( MIM_22         	30.0 )
  ( MIM_23         	35.0 )
  ( active_layer   	"ACTIVE"        )
  ( pdiff_layer    	"ACTIVE"        )
  ( pwell_layer    	"NOTUSED"       )
  ( bondpad_layer  	"NOTUSED"       )
  ( nstrap_layer   	"ACTIVE"        )
  ( pstrap_layer   	"ACTIVE"        )
  ( text_layers    	(("text" "drawing"))	 )
  ( equiv_layers   	nil	 )
  ( pinNetTextLayer	("text" "drawing")	 )
  ( turbo_purposes 	("drawing" "pin")	 )
  ( leTb_min_finger_n	0.18 )
  ( leTb_max_finger_n	3000.0 )
  ( leTb_min_finger_p	0.18 )
  ( leTb_max_finger_p	3000.0 )
  ( leTb_max_ngate_width	100.0 )
  ( leTb_max_ngate_length	10.0 )
  ( leTb_max_pgate_width	100.0 )
  ( leTb_max_pgate_length	10.0 )
  ( leTb_nwell_tie_offset	0.12 )
  ( leTb_pwell_tie_offset	0.0 )
  ( leTb_nplus_tie_offset	0.0 )
  ( leTb_pplus_tie_offset	0.0 )
  ( leTb_ntie_to_ptie	0.0 )
  ( leTb_nwell_tie_overlap_diff	0.43 )
  ( leTb_pwell_tie_overlap_diff	0.0 )
  ( leTb_nplus_tie_overlap_diff	0.02 )
  ( leTb_pplus_tie_overlap_diff	0.02 )
  ( leTb_ndiff_to_nwell_tie	0.86 )
  ( leTb_ndiff_to_pwell_tie	0.0 )
  ( leTb_ndiff_tie_overlap_contact	0.1 )
  ( leTb_pdiff_tie_overlap_contact	0.1 )
  ( leTb_imp_overlap_strap	0.0 )
  ( leTb_cut_type  	2               )
  ( leTb_strap_option	0               )
  ( leTb_pn_separation	0.0 )
  ( LEFDEF_TIME_UNIT	1               )
  ( LEFDEF_OVERLAP_LAYER_NAME	"OverlapCheck"  )
  ( LEFDEF_RESISTANCE_UNIT	1               )
  ( LEFDEF_CAPACITANCE_UNIT	1               )
 ) ;techParams

 viewTypeUnits(
 ;( viewType            userUnit       dbuperuu           )
 ;( --------            --------       --------           )
  ( maskLayout     	"micron"       	1000            )
  ( schematic      	"inch"         	160             )
  ( schematicSymbol	"inch"         	160             )
  ( netlist        	"inch"         	160             )
 ) ;viewTypeUnits

 mfgGridResolution(
      ( 0.005000 )
 ) ;mfgGridResolution

) ;controls


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( dummy                     18         dy           )
  ( high_gain                 24         hg           )
  ( keep_out                  26         kt           )
  ( drc                       27         dc           )
  ( lvs                       28         ls           )
  ( mdp                       29         mp           )
  ( opc                       30         oc           )
  ( no_dummy                  35         ny           )
  ( p2                        39         p2           )
  ( lv_op                     41         lv           )
  ( res                       42         rs           )
  ( cap                       43         cp           )
  ( dio                       44         do           )
  ( seal                      45         sl           )
  ( pad                       46         pd           )
  ( bjt                       47         bt           )
  ( per                       48         pr           )
  ( esd                       50         ed           )
  ( vss                       51         vs           )
  ( res1                      55         r1           )
  ( mim                       56         mm           )
  ( nmim                      57         nm           )
  ( cvs                       58         cs           )
  ( mslits                    59         ms           )
  ( a_bitcell                 60         ab           )
  ( ip                        63         ip           )
  ( ext                       65         et           )
  ( prbdry                    70         py           )
  ( mfc                       73         mc           )
  ( pnrblock                  84         pk           )
  ( t3                        86         t3           )
  ( fix                       93         fx           )
  ( fuse                      105        fe           )
  ( low_voltage               113        le           )
  ( scr                       123        sr           )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( OverlapCheck              0          Overlap      )
  ( WPD                       1          WPD          )
  ( WP                        2          PWELL        )
  ( WN                        3          NWELL        )
  ( WB                        4          WB           )
  ( SDG                       5          SDG          )
  ( PSUB                      6          PSUB         )
  ( DT                        7          DT           )
  ( GC                        8          POLY         )
  ( ACTIVE                    9          ACTIVE       )
  ( CNH                       10         CNH          )
  ( CNS                       11         CNS          )
  ( CPS                       12         CPS          )
  ( WPL                       13         WPL          )
  ( VTH3B                     14         VTH3B        )
  ( VNL                       15         VNL          )
  ( VPL                       16         VPL          )
  ( VNN                       17         VNN          )
  ( VTH6A                     19         VTN23        )
  ( VTH6B                     20         VTP23        )
  ( LVT_PW                    22         NN           )
  ( HN                        23         HN           )
  ( HP                        24         HP           )
  ( W3                        25         W3           )
  ( W4                        26         W4           )
  ( STR_BLK                   27         STR_BLK      )
  ( BL_ST                     28         BL_ST        )
  ( LP                        29         LP           )
  ( LN                        30         LN           )
  ( XP                        31         PPLUS        )
  ( XN                        32         NPLUS        )
  ( CHN                       33         CHN          )
  ( CS                        34         CONT         )
  ( W1                        35         W1           )
  ( W2                        36         W2           )
  ( BIT_LINE                  38         BITLINE      )
  ( MAB                       39         MAB          )
  ( M1                        40         M1           )
  ( V2                        41         VIA2         )
  ( M2                        42         M2           )
  ( V3                        43         VIA3         )
  ( M3                        44         M3           )
  ( TOP_V                     49         TOP_V        )
  ( TOP_M                     50         TOP_M        )
  ( VIAA                      53         VIAT3        )
  ( DRCERR                    60         DRCERR       )
  ( JNL                       61         JNL          )
  ( PIQ                       62         PIQ          )
  ( CB                        63         CB           )
  ( QN                        64         QN           )
  ( CPH                       65         CPH          )
  ( CT                        66         CT           )
  ( PAD                       68         PAD          )
  ( ALP                       69         ALP          )
  ( AREA1                     71         DAREA        )
  ( AREA2                     72         HVAREA       )
  ( AREA5                     75         AREA5        )
  ( AREA6                     76         AREA6        )
  ( DEV_AREA                  77         DEV_AREA     )
  ( SPC_AREA                  78         SPC_AREA     )
  ( TR                        79         TR           )
  ( AREA10                    80         NODRC        )
  ( NODUMMY                   81         NODUMM       )
  ( AREA12                    82         AREA12       )
  ( BLK                       83         BLK          )
  ( RED                       84         RED          )
  ( GRN                       85         GRN          )
  ( BLU                       86         BLU          )
  ( MR                        87         MR           )
  ( NS                        88         NS           )
  ( ULS                       89         ULS          )
  ( FRAME                     90         FRAME        )
  ( VTG                       91         VTG          )
  ( PDN                       92         PDN          )
  ( PDP                       93         PDP          )
  ( PD3                       94         PD3          )
  ( PINMARK                   95         PINMARK      )
  ( CELLNAME                  96         CELLNAME     )
  ( DN2                       97         DN2          )
  ( BCE                       98         BCE          )
  ( CE                        99         CE           )
  ( DPH                       101        DPH          )
  ( Zero                      102        Zero         )
  ( AS                        103        AS           )
  ( PHV                       104        PHV          )
  ( RAA                       105        RAA          )
  ( WM                        106        WM           )
  ( WPV                       107        WPV          )
  ( WPH                       108        WPH          )
  ( Wline                     109        WL           )
  ( L110                      110        GRID1        )
  ( L111                      111        GRID2        )
  ( FB                        112        FB           )
  ( L113                      113        L113         )
  ( L114                      114        L114         )
  ( PLC                       115        PLC          )
  ( ESD5OVT                   116        ESD          )
  ( WNV                       117        WNV          )
  ( WNH                       118        WNH          )
  ( Harea                     119        AH           )
  ( HVP                       120        AL           )
  ( GN                        121        GN           )
  ( BCB                       122        BCB          )
  ( LNV                       123        LNV          )
  ( HVN                       124        HVN          )
  ( LNL                       125        LNL          )
  ( LPV                       126        LPV          )
  ( VNH                       127        VNH          )
  ( LWP                       128        LWP          )
  ( AWP                       129        AWP          )
  ( SWP                       130        SWP          )
  ( MWP                       131        MWP          )
  ( MCN                       132        MCN          )
  ( GT                        133        GT           )
  ( D4                        134        D4           )
  ( VWG                       154        VWG          )
  ( NIC                       155        NIC          )
  ( NPB                       156        NPB          )
  ( LOX                       157        LOX          )
  ( CNL                       162        CNL          )
  ( CPL                       163        CPL          )
  ( MR2                       164        MR2          )
  ( TAP                       185        TAP          )
  ( WN_noconn                 903        NWELL_noconn )
  ( GC_noconn                 908        POLY_noconn  )
  ( ACTIVE_noconn             909        ACTIVE_noconn )
  ( XP_noconn                 931        PPLUS_noconn )
  ( XN_noconn                 932        NPLUS_noconn )
  ( CS_noconn                 934        CONT_noconn  )
  ( M1_noconn                 940        M1_noconn    )
  ( V2_noconn                 941        VIA2_noconn  )
  ( M2_noconn                 942        M2_noconn    )
  ( V3_noconn                 943        VIA3_noconn  )
  ( M3_noconn                 944        M3_noconn    )
  ( TOP_V_noconn              949        TOP_V_noconn )
  ( TOP_M_noconn              950        TOP_M_noconn )
  ( PAD_noconn                968        PAD_noconn   )
  ( ACTIVE_n45                10931      ACTIVE_n45   )
  ( ACTIVE_p45                10932      ACTIVE_p45   )
  ( ACTIVE_n90                10933      ACTIVE_n90   )
  ( ACTIVE_p90                10934      ACTIVE_p90   )
  ( RDL_per                   15848      RDL_per      )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( ACTIVE                    boundary   )
  ( ACTIVE                    pin        )
  ( ACTIVE                    net        )
  ( XP                        boundary   )
  ( XP                        pin        )
  ( XP                        net        )
  ( XN                        boundary   )
  ( XN                        pin        )
  ( XN                        net        )
  ( WN                        boundary   )
  ( WN                        pin        )
  ( WN                        net        )
  ( GC                        boundary   )
  ( TOP_V                     boundary   )
  ( TOP_V                     pin        )
  ( TOP_V                     net        )
  ( V3                        boundary   )
  ( V3                        pin        )
  ( V3                        net        )
  ( V2                        boundary   )
  ( V2                        pin        )
  ( V2                        net        )
  ( TOP_M                     boundary   )
  ( M3                        boundary   )
  ( M2                        boundary   )
  ( M1                        boundary   )
  ( WN                        drawing    )
  ( WN_noconn                 drc        )
  ( WN_noconn                 opc        )
  ( WN_noconn                 dio        )
  ( WN                        vss        )
  ( WB                        drawing    )
  ( WB                        lvs        )
  ( GC                        drawing    )
  ( GC                        label      )
  ( GC                        dummy      )
  ( GC                        pin        )
  ( GC                        net        )
  ( GC_noconn                 opc        )
  ( GC_noconn                 no_dummy   )
  ( GC_noconn                 pnrblock   )
  ( ACTIVE                    drawing    )
  ( ACTIVE                    dummy      )
  ( ACTIVE_noconn             no_dummy   )
  ( ACTIVE_noconn             esd        )
  ( CNH                       drawing    )
  ( VNN                       drawing    )
  ( XP                        drawing    )
  ( XN                        drawing    )
  ( CS                        drawing    )
  ( CS                        grid       )
  ( CS                        blockage   )
  ( M1                        drawing    )
  ( M1                        track      )
  ( M1                        grid       )
  ( M1                        blockage   )
  ( M1                        label      )
  ( M1                        dummy      )
  ( M1                        pin        )
  ( M1                        net        )
  ( M1_noconn                 opc        )
  ( M1_noconn                 no_dummy   )
  ( M1                        vss        )
  ( M1                        res1       )
  ( M1_noconn                 mslits     )
  ( M1_noconn                 pnrblock   )
  ( V2                        drawing    )
  ( V2                        grid       )
  ( V2                        blockage   )
  ( V2_noconn                 pnrblock   )
  ( M2                        drawing    )
  ( M2                        track      )
  ( M2                        grid       )
  ( M2                        blockage   )
  ( M2                        label      )
  ( M2                        dummy      )
  ( M2                        pin        )
  ( M2                        net        )
  ( M2_noconn                 opc        )
  ( M2_noconn                 no_dummy   )
  ( M2                        vss        )
  ( M2                        res1       )
  ( M2_noconn                 mslits     )
  ( M2_noconn                 pnrblock   )
  ( V3                        drawing    )
  ( V3                        grid       )
  ( V3                        blockage   )
  ( V3_noconn                 pnrblock   )
  ( M3                        drawing    )
  ( M3                        track      )
  ( M3                        grid       )
  ( M3                        blockage   )
  ( M3                        label      )
  ( M3                        dummy      )
  ( M3                        pin        )
  ( M3                        net        )
  ( M3_noconn                 opc        )
  ( M3_noconn                 no_dummy   )
  ( M3                        vss        )
  ( M3                        res1       )
  ( M3_noconn                 mslits     )
  ( M3_noconn                 pnrblock   )
  ( TOP_V                     drawing    )
  ( TOP_V                     grid       )
  ( TOP_V                     blockage   )
  ( TOP_V_noconn              pnrblock   )
  ( TOP_M                     drawing    )
  ( TOP_M                     track      )
  ( TOP_M                     grid       )
  ( TOP_M                     blockage   )
  ( TOP_M                     label      )
  ( TOP_M                     dummy      )
  ( TOP_M                     pin        )
  ( TOP_M                     net        )
  ( TOP_M_noconn              lvs        )
  ( TOP_M_noconn              no_dummy   )
  ( TOP_M                     vss        )
  ( TOP_M                     res1       )
  ( TOP_M_noconn              mslits     )
  ( TOP_M_noconn              pnrblock   )
  ( DRCERR                    drawing1   )
  ( DRCERR                    drawing2   )
  ( DRCERR                    drawing3   )
  ( DRCERR                    drawing4   )
  ( DRCERR                    drawing5   )
  ( DRCERR                    drawing6   )
  ( DRCERR                    drawing7   )
  ( DRCERR                    drawing8   )
  ( DRCERR                    drawing9   )
  ( CB                        ip         )
  ( CPH                       drawing    )
  ( PAD                       drawing    )
  ( PAD                       dummy      )
  ( PAD                       pin        )
  ( PAD_noconn                drc        )
  ( AREA2                     drawing    )
  ( AREA6                     drawing    )
  ( AREA6                     mdp        )
  ( DEV_AREA                  high_gain  )
  ( DEV_AREA                  p2         )
  ( DEV_AREA                  lv_op      )
  ( DEV_AREA                  res        )
  ( DEV_AREA                  cap        )
  ( DEV_AREA                  dio        )
  ( DEV_AREA                  seal       )
  ( DEV_AREA                  pad        )
  ( DEV_AREA                  bjt        )
  ( DEV_AREA                  per        )
  ( DEV_AREA                  esd        )
  ( DEV_AREA                  res1       )
  ( DEV_AREA                  mim        )
  ( DEV_AREA                  nmim       )
  ( DEV_AREA                  cvs        )
  ( DEV_AREA                  a_bitcell  )
  ( DEV_AREA                  ext        )
  ( DEV_AREA                  prbdry     )
  ( DEV_AREA                  mfc        )
  ( DEV_AREA                  t3         )
  ( DEV_AREA                  fix        )
  ( DEV_AREA                  low_voltage )
  ( DEV_AREA                  scr        )
  ( SPC_AREA                  cap        )
  ( SPC_AREA                  dio        )
  ( SPC_AREA                  mim        )
  ( SPC_AREA                  ip         )
  ( SPC_AREA                  mfc        )
  ( SPC_AREA                  fuse       )
  ( AREA10                    opc        )
  ( AREA10                    esd        )
  ( AREA10                    mim        )
  ( AREA10                    a_bitcell  )
  ( NODUMMY                   drawing    )
  ( NODUMMY                   ip         )
  ( MR                        drawing    )
  ( NS                        drawing    )
  ( CE                        drawing    )
  ( ESD5OVT                   drawing    )
  ( ESD5OVT                   keep_out   )
  ( ESD5OVT                   esd        )
  ( CNL                       drawing    )
  ( CPL                       drawing    )
  ( MR2                       drawing    )
  ( OverlapCheck              boundary   )
  ( TAP                       drawing    )
  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( Row                       drawing    )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( device                    drawing    )
  ( device                    drawing2   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( device                    annotate   )
  ( device                    label      )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( device                    drawing1   )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( Row                       boundary   )
  ( Unrouted                  track      )
  ( marker                    annotate   )
  ( marker                    info       )
  ( marker                    ackWarn    )
  ( marker                    soError    )
  ( marker                    soCritical )
  ( marker                    critical   )
  ( marker                    fatal      )
  ( Group                     boundary   )
  ( y0                        flight     )
  ( y1                        flight     )
  ( y2                        flight     )
  ( y3                        flight     )
  ( y4                        flight     )
  ( y5                        flight     )
  ( y6                        flight     )
  ( y7                        flight     )
  ( y8                        flight     )
  ( y9                        flight     )
  ( border                    boundary   )
  ( snap                      grid       )
  ( annotate                  boundary   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( snap                      boundary   )
 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( ACTIVE       boundary     defaultPacket    t nil nil nil nil )
  ( ACTIVE       pin          defaultPacket    t nil nil nil nil )
  ( ACTIVE       net          defaultPacket    t nil nil nil nil )
  ( XP           boundary     defaultPacket    t nil nil nil nil )
  ( XP           pin          defaultPacket    t nil nil nil nil )
  ( XP           net          defaultPacket    t nil nil nil nil )
  ( XN           boundary     defaultPacket    t nil nil nil nil )
  ( XN           pin          defaultPacket    t nil nil nil nil )
  ( XN           net          defaultPacket    t nil nil nil nil )
  ( WN           boundary     defaultPacket    t nil nil nil nil )
  ( WN           pin          defaultPacket    t nil nil nil nil )
  ( WN           net          defaultPacket    t nil nil nil nil )
  ( GC           boundary     defaultPacket    t nil nil nil nil )
  ( TOP_V        boundary     defaultPacket    t nil nil nil nil )
  ( TOP_V        pin          defaultPacket    t nil nil nil nil )
  ( TOP_V        net          defaultPacket    t nil nil nil nil )
  ( V3           boundary     defaultPacket    t nil nil nil nil )
  ( V3           pin          defaultPacket    t nil nil nil nil )
  ( V3           net          defaultPacket    t nil nil nil nil )
  ( V2           boundary     defaultPacket    t nil nil nil nil )
  ( V2           pin          defaultPacket    t nil nil nil nil )
  ( V2           net          defaultPacket    t nil nil nil nil )
  ( TOP_M        boundary     defaultPacket    t nil nil nil nil )
  ( M3           boundary     defaultPacket    t nil nil nil nil )
  ( M2           boundary     defaultPacket    t nil nil nil nil )
  ( M1           boundary     defaultPacket    t nil nil nil nil )
  ( WN           drawing      WN_drawing       t t t t t )
  ( WN_noconn    drc          WN_drc           t t t t t )
  ( WN_noconn    opc          WN_opc           t t t t t )
  ( WN_noconn    dio          WN_dio           t t t t t )
  ( WN           vss          WN_vss           t t t t t )
  ( WB           drawing      WB_drawing       t t t t t )
  ( WB           lvs          WB_lvs           t t t t nil )
  ( GC           drawing      GC_drawing       t t t t t )
  ( GC           label        GC_label         t t t t t )
  ( GC           dummy        GC_dummy         t t t t t )
  ( GC           pin          GC_pin           t t t t t )
  ( GC           net          GC_net           t t t t t )
  ( GC_noconn    opc          GC_opc           t t t t t )
  ( GC_noconn    no_dummy     GC_no_dummy      t t t t t )
  ( GC_noconn    pnrblock     GC_pnrblock      t t t t t )
  ( ACTIVE       drawing      ACTIVE_drawing   t t t t t )
  ( ACTIVE       dummy        ACTIVE_dummy     t t t t t )
  ( ACTIVE_noconn no_dummy     ACTIVE_no_dummy  t t t t t )
  ( ACTIVE_noconn esd          ACTIVE_esd       t t t t t )
  ( CNH          drawing      CNH_drawing      t t t t t )
  ( VNN          drawing      VNN_drawing      t t t t t )
  ( XP           drawing      XP_drawing       t t t t t )
  ( XN           drawing      XN_drawing       t t t t t )
  ( CS           drawing      CS_drawing       t t t t t )
  ( CS           grid         CS_drawing       t nil nil nil nil )
  ( CS           blockage     CS_drawing       t nil t t nil )
  ( M1           drawing      M1_drawing       t t t t t )
  ( M1           track        M1_drawing       nil nil t t nil )
  ( M1           grid         M1_drawing       t nil nil nil nil )
  ( M1           blockage     M1_drawing       t nil t t nil )
  ( M1           label        M1_label         t t t t t )
  ( M1           dummy        M1_dummy         t t t t t )
  ( M1           pin          M1_pin           t t t t t )
  ( M1           net          M1_net           t t t t t )
  ( M1_noconn    opc          M1_opc           t t t t t )
  ( M1_noconn    no_dummy     M1_no_dummy      t t t t t )
  ( M1           vss          M1_vss           t t t t t )
  ( M1           res1         M1_res1          t t t t t )
  ( M1_noconn    mslits       M1_mslits        t t t t t )
  ( M1_noconn    pnrblock     M1_pnrblock      t t t t t )
  ( V2           drawing      V2_drawing       t t t t t )
  ( V2           grid         V2_drawing       t nil nil nil nil )
  ( V2           blockage     V2_drawing       t nil t t nil )
  ( V2_noconn    pnrblock     V2_pnrblock      t t t t t )
  ( M2           drawing      M2_drawing       t t t t t )
  ( M2           track        M2_drawing       nil nil t t nil )
  ( M2           grid         M2_drawing       t nil nil nil nil )
  ( M2           blockage     M2_drawing       t nil t t nil )
  ( M2           label        M2_label         t t t t t )
  ( M2           dummy        M2_dummy         t t t t t )
  ( M2           pin          M2_pin           t t t t t )
  ( M2           net          M2_net           t t t t t )
  ( M2_noconn    opc          M2_opc           t t t t t )
  ( M2_noconn    no_dummy     M2_no_dummy      t t t t t )
  ( M2           vss          M2_vss           t t t t t )
  ( M2           res1         M2_res1          t t t t t )
  ( M2_noconn    mslits       M2_mslits        t t t t t )
  ( M2_noconn    pnrblock     M2_pnrblock      t t t t t )
  ( V3           drawing      V3_drawing       t t t t t )
  ( V3           grid         V3_drawing       t nil nil nil nil )
  ( V3           blockage     V3_drawing       t nil t t nil )
  ( V3_noconn    pnrblock     V3_pnrblock      t t t t t )
  ( M3           drawing      M3_drawing       t t t t t )
  ( M3           track        M3_drawing       nil nil t t nil )
  ( M3           grid         M3_drawing       t nil nil nil nil )
  ( M3           blockage     M3_drawing       t nil t t nil )
  ( M3           label        M3_label         t t t t t )
  ( M3           dummy        M3_dummy         t t t t t )
  ( M3           pin          M3_pin           t t t t t )
  ( M3           net          M3_net           t t t t t )
  ( M3_noconn    opc          M3_opc           t t t t t )
  ( M3_noconn    no_dummy     M3_no_dummy      t t t t t )
  ( M3           vss          M3_vss           t t t t t )
  ( M3           res1         M3_res1          t t t t t )
  ( M3_noconn    mslits       M3_mslits        t t t t t )
  ( M3_noconn    pnrblock     M3_pnrblock      t t t t t )
  ( TOP_V        drawing      TOP_V_drawing    t t t t t )
  ( TOP_V        grid         TOP_V_drawing    t nil nil nil nil )
  ( TOP_V        blockage     TOP_V_drawing    t nil t t nil )
  ( TOP_V_noconn pnrblock     TOP_V_pnrblock   t t t t t )
  ( TOP_M        drawing      TOP_M_drawing    t t t t t )
  ( TOP_M        track        TOP_M_drawing    nil nil t t nil )
  ( TOP_M        grid         TOP_M_drawing    t nil nil nil nil )
  ( TOP_M        blockage     TOP_M_drawing    t nil t t nil )
  ( TOP_M        label        TOP_M_label      t t t t t )
  ( TOP_M        dummy        TOP_M_dummy      t t t t t )
  ( TOP_M        pin          TOP_M_pin        t t t t t )
  ( TOP_M        net          TOP_M_net        t t t t t )
  ( TOP_M_noconn lvs          TOP_M_lvs        t t t t t )
  ( TOP_M_noconn no_dummy     TOP_M_no_dummy   t t t t t )
  ( TOP_M        vss          TOP_M_vss        t t t t t )
  ( TOP_M        res1         TOP_M_res1       t t t t t )
  ( TOP_M_noconn mslits       TOP_M_mslits     t t t t t )
  ( TOP_M_noconn pnrblock     TOP_M_pnrblock   t t t t t )
  ( DRCERR       drawing1     DRCERR_drawing1  t t t t nil )
  ( DRCERR       drawing2     DRCERR_drawing2  t t t t nil )
  ( DRCERR       drawing3     DRCERR_drawing3  t t t t nil )
  ( DRCERR       drawing4     DRCERR_drawing4  t t t t nil )
  ( DRCERR       drawing5     DRCERR_drawing5  t t t t nil )
  ( DRCERR       drawing6     DRCERR_drawing6  t t t t nil )
  ( DRCERR       drawing7     DRCERR_drawing7  t t t t nil )
  ( DRCERR       drawing8     DRCERR_drawing8  t t t t nil )
  ( DRCERR       drawing9     DRCERR_drawing9  t t t t nil )
  ( CB           ip           CB_ip            t t t t t )
  ( CPH          drawing      CPH_drawing      t t t t t )
  ( PAD          drawing      PAD_drawing      t t t t t )
  ( PAD          dummy        PAD_dummy        t t t t t )
  ( PAD          pin          PAD_pin          t t t t t )
  ( PAD_noconn   drc          PAD_drc          t t t t t )
  ( AREA2        drawing      AREA2_drawing    t t t t t )
  ( AREA6        drawing      AREA6_drawing    t t t t t )
  ( AREA6        mdp          AREA6_mdp        t t t t t )
  ( DEV_AREA     high_gain    DEV_AREA_high_gain t t t t t )
  ( DEV_AREA     p2           DEV_AREA_p2      t t t t nil )
  ( DEV_AREA     lv_op        DEV_AREA_lv_op   t t t t t )
  ( DEV_AREA     res          DEV_AREA_res     t t t t t )
  ( DEV_AREA     cap          DEV_AREA_cap     t t t t t )
  ( DEV_AREA     dio          DEV_AREA_dio     t t t t t )
  ( DEV_AREA     seal         DEV_AREA_seal    t t t t t )
  ( DEV_AREA     pad          DEV_AREA_pad     t t t t t )
  ( DEV_AREA     bjt          DEV_AREA_bjt     t t t t t )
  ( DEV_AREA     per          DEV_AREA_per     t t t t t )
  ( DEV_AREA     esd          DEV_AREA_esd     t t t t t )
  ( DEV_AREA     res1         DEV_AREA_res1    t t t t t )
  ( DEV_AREA     mim          DEV_AREA_mim     t t t t t )
  ( DEV_AREA     nmim         DEV_AREA_nmim    t t t t t )
  ( DEV_AREA     cvs          DEV_AREA_cvs     t t t t t )
  ( DEV_AREA     a_bitcell    DEV_AREA_a_bitcell t t t t t )
  ( DEV_AREA     ext          DEV_AREA_ext     t t t t t )
  ( DEV_AREA     prbdry       DEV_AREA_prbdry  t t t t t )
  ( DEV_AREA     mfc          DEV_AREA_mfc     t t t t nil )
  ( DEV_AREA     t3           DEV_AREA_t3      t t t t t )
  ( DEV_AREA     fix          DEV_AREA_fix     t t t t nil )
  ( DEV_AREA     low_voltage  DEV_AREA_low_voltage t t t t nil )
  ( DEV_AREA     scr          DEV_AREA_scr     t t t t nil )
  ( SPC_AREA     cap          SPC_AREA_cap     t t t t nil )
  ( SPC_AREA     dio          SPC_AREA_dio     t t t t t )
  ( SPC_AREA     mim          SPC_AREA_mim     t t t t nil )
  ( SPC_AREA     ip           SPC_AREA_ip      t t t t t )
  ( SPC_AREA     mfc          SPC_AREA_mfc     t t t t t )
  ( SPC_AREA     fuse         SPC_AREA_fuse    t t t t nil )
  ( AREA10       opc          AREA10_opc       t t t t t )
  ( AREA10       esd          AREA10_esd       t t t t nil )
  ( AREA10       mim          AREA10_mim       t t t t nil )
  ( AREA10       a_bitcell    AREA10_a_bitcell t t t t t )
  ( NODUMMY      drawing      NODUMMY_drawing  t t t t t )
  ( NODUMMY      ip           NODUMMY_ip       t t t t t )
  ( MR           drawing      MR_drawing       t t t t t )
  ( NS           drawing      NS_drawing       t t t t t )
  ( CE           drawing      CE_drawing       t t t t t )
  ( ESD5OVT      drawing      ESD5OVT_drawing  t t t t t )
  ( ESD5OVT      keep_out     ESD5OVT_keep_out t t t t t )
  ( ESD5OVT      esd          ESD5OVT_esd      t t t t t )
  ( CNL          drawing      CNL_drawing      t t t t nil )
  ( CPL          drawing      CPL_drawing      t t t t nil )
  ( MR2          drawing      MR2_drawing      t t t t nil )
  ( OverlapCheck boundary     OverlapCheck     t nil t t t )
  ( TAP          drawing      TAP_drawing      t t t t t )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        t t t t nil )
  ( instance     drawing      instance         t nil nil t t )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t nil nil t t )
  ( prBoundary   boundary     prBoundaryBnd    t nil nil t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( align        drawing      align            t t nil t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )
  ( Row          label        RowLbl           t t t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t t t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( text         drawing      text             t t t t t )
  ( text         drawing1     text1            t t t t t )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t nil t t t )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t t )
  ( device       drawing1     device1          t t t t nil )
  ( edgeLayer    drawing      edgeLayer        t nil nil t t )
  ( edgeLayer    pin          edgeLayerPin     t t nil t nil )
  ( snap         drawing      snap             t nil nil t t )
  ( stretch      drawing      stretch          t t nil t nil )
  ( y0           drawing      y0               t nil nil t t )
  ( y1           drawing      y1               t nil nil t t )
  ( y2           drawing      y2               t nil nil t t )
  ( y3           drawing      y3               t nil nil t t )
  ( y4           drawing      y4               t nil nil t t )
  ( y5           drawing      y5               t nil nil t t )
  ( y6           drawing      y6               t nil nil t t )
  ( y7           drawing      y7               t nil nil t t )
  ( y8           drawing      y8               t nil nil t t )
  ( y9           drawing      y9               t nil nil t t )
  ( hilite       drawing      hilite           t nil nil t t )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t nil t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t nil t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t t t nil nil )
  ( designFlow   drawing1     designFlow1      t t t nil nil )
  ( designFlow   drawing2     designFlow2      t t t nil nil )
  ( designFlow   drawing3     designFlow3      t t t nil nil )
  ( designFlow   drawing4     designFlow4      t t t nil nil )
  ( designFlow   drawing5     designFlow5      t t t nil nil )
  ( designFlow   drawing6     designFlow6      t t t nil nil )
  ( designFlow   drawing7     designFlow7      t t t nil nil )
  ( designFlow   drawing8     designFlow8      t t t nil nil )
  ( designFlow   drawing9     designFlow9      t t t nil nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
  ( Row          boundary     RowBnd           t t t t nil )
  ( Unrouted     track        UnroutedTrk      t t t t nil )
  ( marker       annotate     markerAno        t t t t nil )
  ( marker       info         markerInf        t t t t nil )
  ( marker       ackWarn      markerAck        t t t t nil )
  ( marker       soError      markerSer        t t t t nil )
  ( marker       soCritical   markerScr        t t t t nil )
  ( marker       critical     markerCrt        t t t t nil )
  ( marker       fatal        markerFat        t t t t nil )
  ( Group        boundary     GroupBnd         t nil t t nil )
  ( y0           flight       y0Flt            t t t t nil )
  ( y1           flight       y1Flt            t t t t nil )
  ( y2           flight       y2Flt            t t t t nil )
  ( y3           flight       y3Flt            t t t t nil )
  ( y4           flight       y4Flt            t t t t nil )
  ( y5           flight       y5Flt            t t t t nil )
  ( y6           flight       y6Flt            t t t t nil )
  ( y7           flight       y7Flt            t t t t nil )
  ( y8           flight       y8Flt            t t t t nil )
  ( y9           flight       y9Flt            t t t t nil )
  ( border       boundary     area             t nil t t nil )
  ( snap         grid         snap             t nil t nil nil )
  ( annotate     boundary     AnnotateBoundary t t t t nil )
  ( changedLayer tool0        changedLayerTl0  t nil nil nil t )
  ( changedLayer tool1        changedLayerTl1  t nil t nil t )
  ( marker       warning      markerWarn       t nil t t t )
  ( marker       error        markerErr        t nil t t t )
  ( background   drawing      blacksolid_S     t t nil nil t )
  ( grid         drawing      slate            t t nil nil t )
  ( grid         drawing1     gray             t t nil nil t )
  ( snap         boundary     snap             t nil t t nil )
 ) ;techDisplays

 techLayerProperties(
 ;( PropName               Layer1 [ Layer2 ]            PropValue )
 ;( --------               ------ ----------            --------- )
  ( areaCapacitance        M1                             3.510000e-05 )
  ( height                 M1                             1.05 )
  ( sheetResistance        M1                             0.080000 )
  ( thickness              M1                             0.54 )
  ( areaCapacitance        M2                             1.460000e-05 )
  ( height                 M2                             2.41 )
  ( sheetResistance        M2                             0.080000 )
  ( thickness              M2                             0.54 )
  ( areaCapacitance        M3                             9.240000e-06 )
  ( height                 M3                             3.77 )
  ( sheetResistance        M3                             0.080000 )
  ( thickness              M3                             0.54 )
  ( areaCapacitance        TOP_M                          4.389000e-06 )
  ( height                 TOP_M                          5.11 )
  ( sheetResistance        TOP_M                          0.040000 )
  ( thickness              TOP_M                          0.84 )
 ) ;techLayerProperties

 techDerivedLayers(
 ;( DerivedLayerName          #          composition  )
 ;( ----------------          ------     ------------ )
  ( noOverlapLayer1           10001      ( GC         'and    ACTIVE    ))
 ) ;techDerivedLayers

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 functions(
 ;( layer                       function        [maskNumber])
 ;( -----                       --------        ------------)
  ( WN                       	"nwell"     	1            )
  ( ACTIVE                   	"ndiff"     	2            )
  ( XP                       	"pplus"     	3            )
  ( XN                       	"nplus"     	4            )
  ( GC                       	"poly"      	5            )
  ( CS                       	"cut"       	6            )
  ( M1                       	"metal"     	7            )
  ( V2                       	"cut"       	8            )
  ( M2                       	"metal"     	9            )
  ( V3                       	"cut"       	10           )
  ( M3                       	"metal"     	11           )
  ( TOP_V                    	"cut"       	12           )
  ( TOP_M                    	"metal"     	13           )
 ) ;functions

 routingDirections(
 ;( layer                       direction     )
 ;( -----                       ---------     )
  ( M1                       	"horizontal" )
  ( M2                       	"vertical"   )
  ( M3                       	"horizontal" )
  ( TOP_M                    	"vertical"   )
 ) ;routingDirections

) ;layerRules


;********************************
; VIADEFS
;********************************
viaDefs(

 standardViaDefs(
 ;( viaDefName	layer1	layer2	(cutLayer cutWidth cutHeight [resistancePerCut]) 
 ;   (cutRows	cutCol	(cutSpace)	[(l_cutPattern)]) 
 ;   (layer1Enc) (layer2Enc)	(layer1Offset)	(layer2Offset)	(origOffset) 
 ;   [implant1	 (implant1Enc)	[implant2	(implant2Enc) [well/substrate]]]) 
 ;( -------------------------------------------------------------------------- ) 
  ( ML_M3_LD    	M3          TOP_M       	("TOP_V" 0.36 0.36)
     (1 2 (0.35 0.35))
     (0.1 0.1)	(0.1 0.1)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M3_M2_LD    	M2          M3          	("V3" 0.26 0.26)
     (1 2 (0.26 0.26))
     (0.1 0.1)	(0.1 0.1)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M2_M1_LD    	M1          M2          	("V2" 0.26 0.26)
     (1 2 (0.26 0.26))
     (0.1 0.1)	(0.1 0.1)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( ML_M3_S     	M3          TOP_M       	("TOP_V" 0.36 0.36)
     (1 1 (0.35 0.35))
     (0.01 0.01)	(0.09 0.09)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M3_M2_S     	M2          M3          	("V3" 0.26 0.26)
     (1 1 (0.26 0.26))
     (0.01 0.01)	(0.01 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M2_M1_S     	M1          M2          	("V2" 0.26 0.26)
     (1 1 (0.26 0.26))
     (0.01 0.01)	(0.01 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( ML_M3       	M3          TOP_M       	("TOP_V" 0.36 0.36)
     (1 2 (0.35 0.35))
     (0.06 0.06)	(0.09 0.09)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M3_M2       	M2          M3          	("V3" 0.26 0.26)
     (1 2 (0.26 0.26))
     (0.06 0.06)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M2_M1       	M1          M2          	("V2" 0.26 0.26)
     (1 2 (0.26 0.26))
     (0.06 0.06)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M1_PO_4X    	GC          M1          	("CS" 0.22 0.22)
     (4 4 (0.28 0.28))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M1_PO       	GC          M1          	("CS" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( PTAP_4X_LG  	ACTIVE      M1          	("CS" 0.22 0.22)
     (4 4 (0.28 0.28))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XP          	(0.18 0.18)
  )
  ( PTAP_4X     	ACTIVE      M1          	("CS" 0.22 0.22)
     (4 4 (0.28 0.28))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XP          	(0.02 0.02)
  )
  ( PTAP_LG     	ACTIVE      M1          	("CS" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XP          	(0.18 0.18)
  )
  ( PTAP        	ACTIVE      M1          	("CS" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XP          	(0.02 0.02)
  )
  ( NTAP_4X_LG  	ACTIVE      M1          	("CS" 0.22 0.22)
     (4 4 (0.28 0.28))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XN          	(0.18 0.18)
  )
  ( NTAP_4X     	ACTIVE      M1          	("CS" 0.22 0.22)
     (4 4 (0.28 0.28))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XN          	(0.02 0.02)
  )
  ( NTAP_LG     	ACTIVE      M1          	("CS" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XN          	(0.18 0.18)
  )
  ( NTAP        	ACTIVE      M1          	("CS" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XN          	(0.02 0.02)
  )
  ( M1_WN       	ACTIVE      M1          	("CS" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     XN          	(0.02 0.02)	WN          	(0.22 0.22)
  )
 ) ;standardViaDefs

) ;viaDefs



;********************************
; CONSTRAINT GROUPS
;********************************
constraintGroups(

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "virtuosoDefaultExtractorSetup"	nil

    interconnect(
     ( validLayers   (TOP_M  TOP_V  M3  V3  M2  V2  M1  CS  GC  ACTIVE  WN  ) )
     ( validVias     (ML_M3_S  M3_M2_S  M2_M1_S  M1_PO_4X  M1_PO  PTAP_4X_LG  PTAP_4X  PTAP_LG  PTAP  NTAP_4X_LG  NTAP_4X  NTAP_LG  NTAP  M1_WN  ) )
     ( errorLayer    noOverlapLayer1 )
    ) ;interconnect
  ) ;virtuosoDefaultExtractorSetup

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "virtuosoDefaultExtractorSetupLargeDies"	nil    nil    'or

    interconnect(
     ( validLayers   (TOP_M  TOP_V  M3  V3  M2  V2  M1  CS  GC  ACTIVE  WN  ) )
     ( validVias     (ML_M3_LD  M3_M2_LD  M2_M1_LD  M1_PO_4X  M1_PO  PTAP_4X_LG  PTAP_4X  PTAP_LG  PTAP  NTAP_4X_LG  NTAP_4X  NTAP_LG  NTAP  M1_WN  ) )
     ( errorLayer    noOverlapLayer1 )
    ) ;interconnect

    orderedSpacings(
     ( minOppExtension            "ACTIVE"	"CS"		'extraCut	(0.12 0.12)  'ref  " minOppExtension ACTIVE CS for more than 1 cut" )
     ( minOppExtension            "ACTIVE"	"CS"		(0.2 0.2)  'ref  " minOppExtension ACTIVE CS " )
     ( minOppExtension            "GC"	"CS"		'extraCut	(0.12 0.12)  'ref  " minOppExtension GC CS for more than 1 cut" )
     ( minOppExtension            "GC"	"CS"		(0.2 0.2)  'ref  " minOppExtension GC CS " )
     ( minOppExtension            "M1"	"CS"		'extraCut	(0.1 0.1)  'ref  "M1.E.1.ISLD"  'description  "Minimum M1 to CS Enclosure for more than 1 cut" )
     ( minOppExtension            "M1"	"CS"		(0.2 0.2)  'ref  " minOppExtension M1 CS " )
     ( minOppExtension            "M1"	"V2"		'extraCut	(0.1 0.1)  'ref  "MI.E.1.ISLD"  'description  "Minimum M1 to V2 Enclosure for more than 1 cut" )
     ( minOppExtension            "M1"	"V2"		(0.2 0.2)  'ref  " minOppExtension M1 V2 " )
     ( minOppExtension            "M2"	"V2"		'extraCut	(0.1 0.1)  'ref  "MI.E.1.ISLD"  'description  "Minimum M2 to V2 Enclosure for more than 1 cut" )
     ( minOppExtension            "M2"	"V2"		(0.2 0.2)  'ref  " minOppExtension M2 V2 " )
     ( minOppExtension            "M2"	"V3"		'extraCut	(0.1 0.1)  'ref  "MI.E.1.ISLD"  'description  "Minimum M2 to V3 Enclosure for more than 1 cut" )
     ( minOppExtension            "M2"	"V3"		(0.2 0.2)  'ref  " minOppExtension M2 V3 " )
     ( minOppExtension            "M3"	"V3"		'extraCut	(0.1 0.1)  'ref  "MI.E.1.ISLD"  'description  "Minimum M3 to V3 Enclosure for more than 1 cut" )
     ( minOppExtension            "M3"	"V3"		(0.2 0.2)  'ref  " minOppExtension M3 V3 " )
     ( minOppExtension            "M3"	"TOP_V"		'extraCut	(0.1 0.1)  'ref  "MI.E.1.ISLD"  'description  "Minimum M3 to TOP_V Enclosure for more than 1 cut" )
     ( minOppExtension            "M3"	"TOP_V"		(0.2 0.2)  'ref  " minOppExtension M3 TOP_V " )
     ( minOppExtension            "TOP_M"	"TOP_V"		'extraCut	(0.1 0.1)  'ref  "ML.E.1.ISLD"  'description  "Minimum TOP_M to TOP_V Enclosure for more than 1 cut" )
     ( minOppExtension            "TOP_M"	"TOP_V"		(0.2 0.2)  'ref  " minOppExtension TOP_M TOP_V " )
    ) ;orderedSpacings
  ) ;virtuosoDefaultExtractorSetupLargeDies

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "virtuosoDefaultSetup"	nil

    interconnect(
     ( validLayers   (TOP_M  M3  M2  M1  ) )
     ( validVias     (ML_M3_S  M3_M2_S  M2_M1_S  ) )
    ) ;interconnect
  ) ;virtuosoDefaultSetup

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "virtuosoDefaultTaper"	nil    "taper"

    interconnect(
     ( validLayers   (GC  M1  ) )
     ( validVias     (M1_PO_4X  M1_PO  ) )
    ) ;interconnect

    spacings(
     ( taperHalo                  1.4 )
    ) ;spacings
  ) ;virtuosoDefaultTaper

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "VLMDefaultSetup"	nil

    interconnect(
     ( validLayers   (TOP_M  TOP_V  M3  V3  M2  V2  M1  CS  GC  ACTIVE  WN  ) )
     ( validVias     (ML_M3_S  M3_M2_S  M2_M1_S  M1_PO_4X  M1_PO  PTAP_4X_LG  PTAP_4X  PTAP_LG  PTAP  NTAP_4X_LG  NTAP_4X  NTAP_LG  NTAP  ) )
    ) ;interconnect
  ) ;VLMDefaultSetup

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "AbstractDefaultSetup"	nil    "LEFDefaultRouteSpec"

    interconnect(
     ( validLayers   (M1  M2  M3  TOP_M  ) )
     ( validVias     (ML_M3_S  M3_M2_S  M2_M1_S  ) )
    ) ;interconnect

    routingGrids(
     ( verticalPitch              "M1"	0.56 )
     ( horizontalPitch            "M1"	0.56 )
     ( verticalOffset             "M1"	0.28 )
     ( verticalPitch              "M2"	0.56 )
     ( horizontalPitch            "M2"	0.56 )
     ( horizontalOffset           "M2"	0.28 )
     ( verticalPitch              "M3"	0.56 )
     ( horizontalPitch            "M3"	0.56 )
     ( verticalOffset             "M3"	0.28 )
     ( verticalPitch              "TOP_M"	1.12 )
     ( horizontalPitch            "TOP_M"	1.12 )
     ( horizontalOffset           "TOP_M"	0.56 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M1"	0.23  'ref  " minWidth M1" )
     ( minWidth                   "M2"	0.28  'ref  " minWidth M2" )
     ( minWidth                   "M3"	0.28  'ref  " minWidth M3" )
     ( minWidth                   "TOP_M"	0.44  'ref  " minWidth TOP_M" )
    ) ;spacings
  ) ;AbstractDefaultSetup

 ;( group	[override]	[definition]	[operator] )
 ;( -----	----------	------------	---------- )
  ( "foundry"	nil

    interconnect(
     ( validVias     (ML_M3_S  M3_M2_S  M2_M1_S  M1_PO  M1_PO_4X  PTAP  PTAP_4X  PTAP_4X_LG  PTAP_LG  NTAP  NTAP_4X  NTAP_4X_LG  NTAP_LG  M1_WN  ) )
    ) ;interconnect

    spacings(
     ( minWidth                   "WN"	0.86  'ref  " minWidth WN" )
     ( minWidth                   "ACTIVE"	0.22  'ref  " minWidth ACTIVE" )
     ( minWidth                   "GC"	0.18  'ref  " minWidth GC" )
     ( minWidth                   "XP"	0.44  'ref  " minWidth XP" )
     ( minWidth                   "XN"	0.44  'ref  " minWidth XN" )
     ( minWidth                   "CS"	0.22  'ref  " minWidth CS" )
     ( minWidth                   "V2"	0.26  'ref  " minWidth V2" )
     ( minWidth                   "V3"	0.26  'ref  " minWidth V3" )
     ( minWidth                   "TOP_V"	0.36  'ref  " minWidth TOP_V" )
     ( minWidth                   "M1"	0.23  'ref  " minWidth M1" )
     ( minWidth                   "M2"	0.28  'ref  " minWidth M2" )
     ( minWidth                   "M3"	0.28  'ref  " minWidth M3" )
     ( minWidth                   "TOP_M"	0.44  'ref  " minWidth TOP_M" )
     ( minSpacing                 "CS"	0.25  'ref  " minSpacing CS" )
     ( minSpacing                 "TOP_V"	0.35  'ref  " minSpacing TOP_V" )
     ( minSpacing                 "V2"	0.26  'ref  " minSpacing V2" )
     ( minSpacing                 "V3"	0.26  'ref  " minSpacing V3" )
     ( minSpacing                 "GC"	"AREA2"		0.4  'ref  " minSpacing GC AREA2" )
     ( minSpacing                 "GC"	"ACTIVE"		0.1  'ref  " minSpacing GC ACTIVE" )
     ( minSpacing                 "XP"	"ACTIVE"		0.26  'ref  " minSpacing XP ACTIVE" )
     ( minSpacing                 "XN"	"ACTIVE"		0.26  'ref  " minSpacing XN ACTIVE" )
     ( minSpacing                 "ACTIVE"	"WN"		0.43  'ref  " minSpacing ACTIVE WN" )
     ( minArea                    "M1"	0.202  'ref  " minArea M1" )
     ( minArea                    "M2"	0.202  'ref  " minArea M2" )
     ( minArea                    "M3"	0.202  'ref  " minArea M3" )
     ( minArea                    "TOP_M"	0.562  'ref  " minArea TOP_M" )
     ( minSameNetSpacing          "M1"	0.23  'ref  " minSameNetSpacing M1" )
     ( minSameNetSpacing          "M2"	0.28  'ref  " minSameNetSpacing M2" )
     ( minSameNetSpacing          "M3"	0.28  'ref  " minSameNetSpacing M3" )
     ( minSameNetSpacing          "TOP_M"	0.46  'ref  " minSameNetSpacing TOP_M" )
     ( minSameNetSpacing          "V2"	0.26  'ref  " minSameNetSpacing V2" )
     ( minSameNetSpacing          "V3"	"V2"		0.0  'ref  " minSameNetSpacing V3 V2" )
     ( minSameNetSpacing          "V3"	0.26  'ref  " minSameNetSpacing V3" )
     ( minSameNetSpacing          "TOP_V"	0.35  'ref  " minSameNetSpacing TOP_V" )
     ( minWidth                   ("GC" "drawing")	0.18  'ref  " minWidth GC drawing" )
     ( minWidth                   ("M1" "drawing")	0.23  'ref  " minWidth M1 drawing" )
     ( minWidth                   ("M2" "drawing")	0.28  'ref  " minWidth M2 drawing" )
     ( minWidth                   ("M3" "drawing")	0.28  'ref  " minWidth M3 drawing" )
     ( minWidth                   ("TOP_M" "drawing")	0.44  'ref  " minWidth TOP_M drawing" )
     ( minSpacing                 ("GC" "drawing")	0.25  'ref  " minSpacing GC drawing" )
     ( minSpacing                 ("M1" "drawing")	0.23  'ref  " minSpacing M1 drawing" )
     ( minSpacing                 ("M2" "drawing")	0.28  'ref  " minSpacing M2 drawing" )
     ( minSpacing                 ("M3" "drawing")	0.28  'ref  " minSpacing M3 drawing" )
     ( minSpacing                 ("TOP_M" "drawing")	0.46  'ref  " minSpacing TOP_M drawing" )
     ( minSpacing                 ("V2" "drawing")	0.26  'ref  " minSpacing V2 drawing" )
     ( minSpacing                 ("V3" "drawing")	0.26  'ref  " minSpacing V3 drawing" )
     ( minSpacing                 ("CS" "drawing")	0.25  'ref  " minSpacing CS drawing" )
    ) ;spacings

    orderedSpacings(
     ( minOppExtension            "GC"	"CS"		(0.1 0.1)  'ref  " minOppExtension GC CS " )
     ( minOppExtension            "M1"	"CS"		(0.06 0.005)  'ref  " minOppExtension M1 CS " )
     ( minOppExtension            "M1"	"V2"		(0.06 0.01)  'ref  " minOppExtension M1 V2 " )
     ( minOppExtension            "M2"	"V2"		(0.06 0.01)  'ref  " minOppExtension M2 V2 " )
     ( minOppExtension            "M2"	"V3"		(0.06 0.01)  'ref  " minOppExtension M2 V3 " )
     ( minOppExtension            "M3"	"V3"		(0.06 0.01)  'ref  " minOppExtension M3 V3 " )
     ( minOppExtension            "M3"	"TOP_V"		(0.06 0.01)  'ref  " minOppExtension M3 TOP_V " )
     ( minOppExtension            "TOP_M"	"TOP_V"		(0.09 0.09)  'ref  " minOppExtension TOP_M TOP_V " )
    ) ;orderedSpacings

    spacings(
     ( stackable                  "V3"	"V2"		t )
     ( stackable                  "TOP_V"	"V3"		t )
    ) ;spacings

    spacingTables(
    ;( constraint 		layer1 		    [layer2]
    ;   (( index1Definitions    [index2Defintions]) [defaultValue] )
    ;   ( table) )
    ;( --------------------------------------------)
     ( minSpacing                "M1"	
	(( "width" nil nil )	0.23 )
         (
            0.0       0.23      
            10.0      0.6       
         )
     )
     ( minSpacing                "M2"	
	(( "width" nil nil )	0.28 )
         (
            0.0       0.28      
            10.0      0.6       
         )
     )
     ( minSpacing                "M3"	
	(( "width" nil nil )	0.28 )
         (
            0.0       0.28      
            10.0      0.6       
         )
     )
     ( minSpacing                "TOP_M"	
	(( "width" nil nil )	0.46 )
         (
            0.0       0.46      
            10.0      0.6       
         )
     )
    ) ;spacingTables

    spacings(
     ( minSameNetSpacing          "WN"	0.6  'ref  " minSameNetSpacing WN" )
     ( minSpacing                 "V2"	"CS"		0.0  'ref  " minSpacing V2 CS" )
    ) ;spacings

    orderedSpacings(
     ( minOverlapDistance         "GC"	"ACTIVE"		0.22  'ref  " minOverlapDistance GC ACTIVE" )
     ( minOppExtension            "ACTIVE"	"CS"		(0.1 0.1)  'ref  " minOppExtension ACTIVE CS " )
    ) ;orderedSpacings

    spacings(
     ( minSpacing                 "ACTIVE"	0.28  'ref  " minSpacing ACTIVE" )
     ( minSpacing                 "XN"	0.44  'ref  " minSpacing XN" )
     ( minSpacing                 "XP"	0.44  'ref  " minSpacing XP" )
     ( minSpacing                 "WN"	2.8  'ref  " minSpacing WN" )
     ( minSpacing                 "GC"	0.25  'ref  " minSpacing GC" )
     ( minSpacing                 "CS"	0.25  'ref  " minSpacing CS" )
     ( minSpacing                 "M1"	0.23  'ref  " minSpacing M1" )
     ( minSpacing                 "M2"	0.28  'ref  " minSpacing M2" )
     ( minSpacing                 "M3"	0.28  'ref  " minSpacing M3" )
     ( minSpacing                 "TOP_M"	0.46  'ref  " minSpacing TOP_M" )
    ) ;spacings

    orderedSpacings(
     ( minExtensionDistance       "ACTIVE"	"CS"		0.1  'ref  " minExtensionDistance ACTIVE CS" )
     ( minExtensionDistance       "GC"	"CS"		0.1  'ref  " minExtensionDistance GC CS" )
     ( minExtensionDistance       "M1"	"CS"		0.005  'ref  " minExtensionDistance M1 CS" )
     ( minExtensionDistance       "M1"	"V2"		0.01  'ref  " minExtensionDistance M1 V2" )
     ( minExtensionDistance       "M2"	"V2"		0.01  'ref  " minExtensionDistance M2 V2" )
     ( minExtensionDistance       "M2"	"V3"		0.01  'ref  " minExtensionDistance M2 V3" )
     ( minExtensionDistance       "M3"	"V3"		0.01  'ref  " minExtensionDistance M3 V3" )
     ( minExtensionDistance       "M3"	"TOP_V"		0.01  'ref  " minExtensionDistance M3 TOP_V" )
     ( minExtensionDistance       "TOP_M"	"TOP_V"		0.09  'ref  " minExtensionDistance TOP_M TOP_V" )
     ( minExtensionDistance       "WN"	"ACTIVE"		0.43  'ref  " minExtensionDistance WN ACTIVE" )
     ( minExtensionDistance       "XP"	"ACTIVE"		0.02  'ref  " minExtensionDistance XP ACTIVE" )
     ( minExtensionDistance       "XN"	"ACTIVE"		0.02  'ref  " minExtensionDistance XN ACTIVE" )
    ) ;orderedSpacings

    spacings(
     ( minSpacing                 "XN"	"XP"		0.0  'ref  " minSpacing XN XP" )
    ) ;spacings

    orderedSpacings(
     ( minExtensionDistance       "ACTIVE"	"GC"		0.32  'ref  " minExtensionDistance ACTIVE GC" )
    ) ;orderedSpacings

    spacings(
     ( minSpacing                 "CS"	"GC"		0.16  'ref  " minSpacing CS GC" )
     ( minSameNetSpacing          "XN"	0.31  'ref  " minSameNetSpacing XN" )
     ( minSameNetSpacing          "XP"	0.31  'ref  " minSameNetSpacing XP" )
    ) ;spacings

    antennaModels(
    ;( model )
    ;( ----- )
     ( "default"
       antenna(
	( areaRatio          "M1"       400.0 'side )
	( diffAreaRatio      "M1"
	   (
	      ( 0.0 400.0 )
	      ( 0.203 400.0 )
	      ( 0.203001 2281.2 )
	      ( 1.203 2681.2 )
	   ) 
	'side )
       ) ;antenna
       antenna(
	( areaRatio          "V2"     20.0 )
	( diffAreaRatio      "V2"
	   (
	      ( 0.0 20.0 )
	      ( 0.203 20.0 )
	      ( 0.203001 91.9161 )
	      ( 1.203 175.246 )
	   ) 
	)
       ) ;antenna
       antenna(
	( areaRatio          "M2"       400.0 'side )
	( diffAreaRatio      "M2"
	   (
	      ( 0.0 400.0 )
	      ( 0.203 400.0 )
	      ( 0.203001 2281.2 )
	      ( 1.203 2681.2 )
	   ) 
	'side )
       ) ;antenna
       antenna(
	( areaRatio          "V3"     20.0 )
	( diffAreaRatio      "V3"
	   (
	      ( 0.0 20.0 )
	      ( 0.203 20.0 )
	      ( 0.203001 91.9161 )
	      ( 1.203 175.246 )
	   ) 
	)
       ) ;antenna
       antenna(
	( areaRatio          "M3"       400.0 'side )
	( diffAreaRatio      "M3"
	   (
	      ( 0.0 400.0 )
	      ( 0.203 400.0 )
	      ( 0.203001 2281.2 )
	      ( 1.203 2681.2 )
	   ) 
	'side )
       ) ;antenna
       antenna(
	( areaRatio          "TOP_V"     20.0 )
	( diffAreaRatio      "TOP_V"
	   (
	      ( 0.0 20.0 )
	      ( 0.203 20.0 )
	      ( 0.203001 91.9161 )
	      ( 1.203 175.246 )
	   ) 
	)
       ) ;antenna
       antenna(
	( areaRatio          "TOP_M"       400.0 'side )
	( diffAreaRatio      "TOP_M"
	   (
	      ( 0.0 400.0 )
	      ( 0.203 400.0 )
	      ( 0.203001 31624.0 )
	      ( 1.203 39624.0 )
	   ) 
	'side )
       ) ;antenna
       cumulativeMetalAntenna(
	( areaRatio                 0.0 'side )
       ) ;cumulativeMetalAntenna
       cumulativeViaAntenna(
	( areaRatio               0.0 )
       ) ;cumulativeViaAntenna
     ) ;default
    ) ;antennaModels
  ) ;foundry
) ;constraintGroups


;********************************
; DEVICES
;********************************
devices(
tcCreateCDSDeviceClass()





multipartPathTemplates(
; ( name [masterPath] [offsetSubpaths] [encSubPaths] [subRects] )
; 
;   masterPath:
;   (layer [width] [choppable] [endType] [beginExt] [endExt] [justify] [offset]
;   [connectivity])
; 
;   offsetSubpaths:
;   (layer [width] [choppable] [separation] [justification] [begOffset] [endOffset]
;   [connectivity])
; 
;   encSubPaths:
;   (layer [enclosure] [choppable] [begOffset] [endOffset]
;   [connectivity])
; 
;   subRects:
;   (layer [width] [length] [choppable] [separation] [justification] [space] [begOffset] [endOffset] [gap] 
;   [connectivity] [beginSegOffset] [endSegOffset])
; 
;   connectivity:
;   ([I/O type] [pin] [accDir] [dispPinName] [height] [ layer]
;    [layer] [justification] [font] [textOptions] [orientation]
;    [refHandle] [offset])
; 
; ( --------------------------------------------------------------------- )
  (GC_M1 
    (("GC" "drawing")	(techParam("_8A") + (2 * techParam("_8D")))	t)
    ((("M1" "drawing")	(techParam("_8A") + (2 * techParam("_9C1")))	t	0         	center	(- (techParam("_8D") - techParam("_9C3")))	
     (minus	(techParam("_8D") - techParam("_9C3"))	))
    )
    nil
    ((("CS" "drawing")	techParam("_8A")	techParam("_8A")	t	0         	center	techParam("_8B")	(- techParam("_8D"))	(- techParam("_8D"))	distribute)
    )
  )
  ("GC_M1 - abut" 
    (("GC" "drawing")	(techParam("_8A") + (2 * techParam("_8D")))	t)
    ((("M1" "drawing")	(techParam("_8A") + (2 * techParam("_9C1")))	t	0         	center	(techParam("_8D") - techParam("_9C1"))	
     (difference	techParam("_8D")	techParam("_9C1")	))
    )
    nil
    ((("CS" "drawing")	techParam("_8A")	techParam("_8A")	t	0         	center	techParam("_8B")	(- (techParam("_8B") - techParam("_8D")))	(- (techParam("_8B") - techParam("_8D")))	distribute)
    )
  )
  (M1_M2 
    (("M1" "drawing")	(techParam("_10A") + (2 * techParam("_10C1")))	t)
    ((("M2" "drawing")	(techParam("_10A") + (2 * techParam("_10C1")))	t	0         	center	0         	0         )
    )
    nil
    ((("V2" "drawing")	techParam("_10A")	techParam("_10A")	t	0         	center	techParam("_10B")	(- techParam("_10C3"))	(- techParam("_10C3"))	distribute)
    )
  )
  (M2_M3 
    (("M2" "drawing")	(techParam("_12A") + (2 * techParam("_12C1")))	t)
    ((("M3" "drawing")	(techParam("_12A") + (2 * techParam("_12C1")))	t	0         	center	0         	0         )
    )
    nil
    ((("V3" "drawing")	techParam("_12A")	techParam("_12A")	t	0         	center	techParam("_12B")	(- techParam("_12C3"))	(- techParam("_12C3"))	distribute)
    )
  )
  (M3_ML 
    (("M3" "drawing")	(techParam("_18A") + (2 * techParam("_18C1")))	t)
    ((("TOP_M" "drawing")	(techParam("_19A") + (2 * techParam("_19C1")))	t	0         	center	0         	0         )
    )
    nil
    ((("TOP_V" "drawing")	techParam("_18A")	techParam("_18A")	t	0         	center	techParam("_18B")	(- techParam("_18C3"))	(- techParam("_18C3"))	distribute)
    )
  )
  ("NWELL Tap" 
    (("ACTIVE" "drawing")	(techParam("_8A") + (2 * techParam("_8C")))	t)
    ((("M1" "drawing")	(techParam("_8A") + (2 * techParam("_9C1")))	t	0         	center	(- (techParam("_8C") - techParam("_9C3")))	
     (minus	(techParam("_8C") - techParam("_9C3"))	))
    )
    ((("XN" "drawing")	(- techParam("XN_L"))	t)
    )
    ((("CS" "drawing")	techParam("_8A")	techParam("_8A")	t	0         	center	techParam("_8B")	(- techParam("_8C"))	(- techParam("_8C"))	distribute)
    )
  )
  ("PWELL Tap" 
    (("ACTIVE" "drawing")	(techParam("_8A") + (2 * techParam("_8C")))	t)
    ((("M1" "drawing")	(techParam("_8A") + (2 * techParam("_9C1")))	t	0         	center	(- (techParam("_8C") - techParam("_9C3")))	
     (minus	(techParam("_8C") - techParam("_9C3"))	))
    )
    ((("XP" "drawing")	(- techParam("_7D"))	t)
    )
    ((("CS" "drawing")	techParam("_8A")	techParam("_8A")	t	0         	center	techParam("_8B")	(- techParam("_8C"))	(- techParam("_8C"))	distribute)
    )
  )
  ("NWELL RING" 
    (("ACTIVE" "drawing")	0.42	nil	truncate	0.0	0.0	center	0.0)
    ((("M1" "drawing")	0.34	t	0.0	center	0.0	0.0)
    )
    ((("XN" "drawing")	-0.18	nil	0.0	0.0)
     (("WN" "drawing")	-0.44	nil	0.0	0.0)
    )
    ((("CS" "drawing")	0.22	0.22	t	0.0	center	0.25	-0.13	-0.13	distribute	nil	0.0	0.0)
    )
  )
  ("PWELL RING" 
    (("ACTIVE" "drawing")	0.42	nil	truncate	0.0	0.0	center	0.0)
    ((("M1" "drawing")	0.34	t	0.0	center	0.0	0.0)
    )
    ((("XP" "drawing")	-0.18	nil	0.0	0.0)
    )
    ((("CS" "drawing")	0.22	0.22	t	0.0	center	0.25	-0.13	-0.13	distribute	nil	0.0	0.0)
    )
  )
)  ;multipartPathTemplates




) ;devices
