// Verilog-AMS netlist generated by Affirma AMS.
// Cadence Design Systems, Inc.

`include "disciplines.vams"
`include "constants.vams"
 
module presistor ( PLUS,MINUS ); 

inout   PLUS;
inout   MINUS;

parameter hrc=0;
parameter dtemp=0;
parameter resform=0;
parameter r=1K;
parameter isnoisy="yes";
parameter m=1;
parameter trise=0;
parameter layer="met1";
parameter tc1=0;
parameter model=0;
parameter c=0;
parameter w=1u;
parameter tc2=0;
parameter ac=0;
parameter l=2u;
parameter scale=0;
 
 
 
capacitor #(.c(c / 2.))  (* integer library_binding = "analogLib";  *) 
C2 ( MINUS, cds_globals.\gnd!  );
capacitor #(.c(c / 2.))  (* integer library_binding = "analogLib";  *) 
C1 ( PLUS, cds_globals.\gnd!  );
 
resistor #(.r(r))  (* integer library_binding = "analogLib";  *) R0 ( PLUS, MINUS );

endmodule
