
// Generated by Cadence Genus(TM) Synthesis Solution 22.15-s086_1
// Generated on: May  6 2026 19:22:47 CEST (May  6 2026 17:22:47 UTC)

// Verification Directory fv/clk_divider_v2 

module clk_divider_v2(clk_50m, rst_n, clk_line, clk_line_pulse);
  input clk_50m, rst_n;
  output clk_line, clk_line_pulse;
  wire clk_50m, rst_n;
  wire clk_line, clk_line_pulse;
  wire [12:0] cnt;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire rst_n_sync, rst_sync_meta;
  dfcrq1 \cnt_reg[12] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_31), .Q
       (cnt[12]));
  oan211d1 g765__2398(.A (n_23), .B (n_30), .C1 (n_29), .C2 (cnt[12]),
       .ZN (n_31));
  dfcrq1 \cnt_reg[11] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_28), .Q
       (cnt[11]));
  nd02d1 g767__5107(.A1 (n_29), .A2 (cnt[12]), .ZN (n_30));
  ora21d1 g768__6260(.A (n_29), .B1 (n_27), .B2 (cnt[11]), .Z (n_28));
  nd02d1 g770__4319(.A1 (n_27), .A2 (cnt[11]), .ZN (n_29));
  dfcrq1 \cnt_reg[10] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_26), .Q
       (cnt[10]));
  dfcrq1 \cnt_reg[9] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_25), .Q
       (cnt[9]));
  ah01d1 g771__8428(.A (n_24), .B (cnt[10]), .CO (n_27), .S (n_26));
  aoim211d1 g773__5526(.A (n_24), .B (n_23), .C1 (n_21), .C2 (cnt[9]),
       .ZN (n_25));
  dfcrq1 \cnt_reg[8] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_22), .Q
       (cnt[8]));
  aoim211d1 g776__6783(.A (n_21), .B (n_23), .C1 (n_19), .C2 (cnt[8]),
       .ZN (n_22));
  dfcrq1 \cnt_reg[7] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_20), .Q
       (cnt[7]));
  an02d1 g775__3680(.A1 (n_21), .A2 (cnt[9]), .Z (n_24));
  aoim211d1 g779__1617(.A (n_23), .B (n_19), .C1 (n_18), .C2 (cnt[7]),
       .ZN (n_20));
  an02d1 g778__2802(.A1 (n_19), .A2 (cnt[8]), .Z (n_21));
  an02d1 g781__1705(.A1 (n_18), .A2 (cnt[7]), .Z (n_19));
  dfcrq1 \cnt_reg[6] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_17), .Q
       (cnt[6]));
  ah01d1 g782__5122(.A (n_15), .B (cnt[6]), .CO (n_18), .S (n_17));
  dfcrq1 \cnt_reg[5] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_16), .Q
       (cnt[5]));
  ah01d1 g784__8246(.A (n_11), .B (cnt[5]), .CO (n_15), .S (n_16));
  dfcrq1 clk_line_reg(.CDN (rst_n_sync), .CP (clk_50m), .D (n_14), .Q
       (clk_line));
  dfcrq1 \cnt_reg[3] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_13), .Q
       (cnt[3]));
  dfcrq1 \cnt_reg[4] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_12), .Q
       (cnt[4]));
  mx02d1 g789__7098(.I0 (n_23), .I1 (n_9), .S (clk_line), .Z (n_14));
  aoim211d1 g791__6131(.A (n_23), .B (n_10), .C1 (n_8), .C2 (cnt[3]),
       .ZN (n_13));
  ah01d1 g787__1881(.A (n_10), .B (cnt[4]), .CO (n_11), .S (n_12));
  dfcrq1 clk_line_pulse_reg(.CDN (rst_n_sync), .CP (clk_50m), .D
       (n_23), .Q (clk_line_pulse));
  inv0d0 g792(.I (n_23), .ZN (n_9));
  an02d1 g793__5115(.A1 (n_7), .A2 (n_8), .Z (n_23));
  an02d1 g797__7482(.A1 (n_8), .A2 (cnt[3]), .Z (n_10));
  dfcrq1 \cnt_reg[2] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_6), .Q
       (cnt[2]));
  nr03d1 g794__4733(.A1 (cnt[11]), .A2 (cnt[10]), .A3 (n_5), .ZN (n_7));
  ah01d1 g798__6161(.A (n_3), .B (cnt[2]), .CO (n_8), .S (n_6));
  nd04d1 g796__9315(.A1 (cnt[7]), .A2 (n_2), .A3 (cnt[9]), .A4
       (cnt[8]), .ZN (n_5));
  dfcrq1 \cnt_reg[1] (.CDN (rst_n_sync), .CP (clk_50m), .D (n_4), .Q
       (cnt[1]));
  ah01d1 g801__9945(.A (cnt[1]), .B (n_0), .CO (n_3), .S (n_4));
  nr04d1 g800__2883(.A1 (cnt[6]), .A2 (cnt[5]), .A3 (cnt[4]), .A4
       (n_1), .ZN (n_2));
  dfcrq1 rst_n_sync_reg(.CDN (rst_n), .CP (clk_50m), .D
       (rst_sync_meta), .Q (rst_n_sync));
  nd12d1 g805__2346(.A1 (cnt[3]), .A2 (cnt[12]), .ZN (n_1));
  dfcrq1 rst_sync_meta_reg(.CDN (rst_n), .CP (clk_50m), .D (1'b1), .Q
       (rst_sync_meta));
  dfcrb1 \cnt_reg[0] (.CDN (rst_n_sync), .CP (clk_50m), .D (cnt[0]), .Q
       (n_0), .QN (cnt[0]));
endmodule

