#! /bin/csh -f

# $Id: rds_tool_config 1 2019/07/01 11:07:32 GMT ronenha Exp $
# $Log: Revision 1 2019/07/01 11:07:32 GMT ronenha $
#   Initial revision.
# 
#  Revision: 1.5 Mon Nov 17 18:00:51 2003 milkovr
#  Settings moved to $RDS_CUSTOM/bin/
# 
#  Revision: 1.4 Thu Jul 10 18:33:25 2003 tomf
#  Changed default Apollo version from 98.4 to 2000.2.9
#  
# Revision 1.3  2002/11/05 23:08:42  milkovr
# Removed HP specific settings that are no longer needed.
#
# Revision 1.2  2002/09/12 00:53:40  knightm
# Change ads version to v2002
#
# Revision 1.1  2002/06/27 14:49:30  milkovr
# Initial revision
