//****************************************************************************//
// Verilog models generated by SiliconSmart P-2019.06-2 build date: Jul 18, 2019 14:03:53. (SMSC-2) //
// Siliconsmart Path: /apps/snps/SiliconSmart-2019.06-2/siliconsmart/P-2019.06-2/linux64/bin/siliconsmart //
// Host Name: edas15fc.corp.towersemi.com, User Name: avipa, PID: 10548       //
// Directory: /direct/sos_proj/ip/NDC/ts18sl_oa_ips/work_libs/avipa/cds/io_conversion/lib_flow_50_scl //
//                                                                            //
// File generated on Wed Mar 01 09:08:45 IST 2023. (SMSC-3)                   //
//****************************************************************************//


`timescale 1ns/1ps




`celldefine
module PAH_50_NA_func( PAD, PADR );
   input PAD;
   output PADR;
   buf MGM_BG_0( PADR, PAD );


endmodule
`endcelldefine



`celldefine
module PAN_50_NA_func( PAD, PADR );
   output PAD, PADR;
   assign PAD = 1'b0;
   assign PADR = 1'b0;


endmodule
`endcelldefine


primitive UDP_ff_5p5v_5p5v_m40c_PIOHO_50_50_UDP_0( MGM_WB_0, EN, PULL_ON, I, PULL_UP_DOWN );
  output MGM_WB_0;
  input EN, PULL_ON, I, PULL_UP_DOWN;
  table
  //EN, PULL_ON, I, PULL_UP_DOWN: MGM_WB_0
    1  0  1  ?: 1;
    0  1  ?  1: 1;
    1  0  0  ?: 0;
    0  1  ?  0: 0;
    1  1  ?  ?: x;
  endtable
endprimitive



`celldefine
module PIOHO_50_50_func( PAD, SCHM_ON, EN, IE, I, VDDO_OK, PULL_UP_DOWN, PULL_ON, TTL_ON, DRIVE_STR, VDD_OK, CIN );
   input DRIVE_STR, EN, I, IE, PULL_ON, PULL_UP_DOWN, SCHM_ON, TTL_ON, VDDO_OK, VDD_OK;
   output CIN;
   inout PAD;
   and MGM_BG_0( CIN, IE, PAD );
// wire MGM_WB_0;
// wire MGM_WB_1;
// UDP_ff_5p5v_5p5v_m40c_PIOHO_50_50_UDP_0( MGM_WB_0, EN, PULL_ON, I, PULL_UP_DOWN );
// wire EN_inv_for_PIOHO_50_50;
// not MGM_BG_1( EN_inv_for_PIOHO_50_50, EN );
// wire PULL_ON_inv_for_PIOHO_50_50;
// not MGM_BG_2( PULL_ON_inv_for_PIOHO_50_50, PULL_ON );
// and MGM_BG_3( MGM_WB_1, EN_inv_for_PIOHO_50_50, PULL_ON_inv_for_PIOHO_50_50 );
// bufif0 MGM_BG_4( PAD, MGM_WB_0,MGM_WB_1 );
   bufif1 (weak0,weak1) (PAD, PULL_UP_DOWN, PULL_ON) ;
   bufif1 (PAD, I, EN) ;


endmodule
`endcelldefine



`celldefine
module PIOH_50_50_func( PAD, SCHM_ON, EN, IE, VDDO_OK, I, PULL_UP_DOWN, PULL_ON, TTL_ON, DRIVE_STR, VDD_OK, CIN );
   input DRIVE_STR, EN, I, IE, PULL_ON, PULL_UP_DOWN, SCHM_ON, TTL_ON, VDDO_OK, VDD_OK;
   output CIN;
   inout PAD;
   and MGM_BG_0( CIN, IE, PAD );
// wire MGM_WB_0;
// wire MGM_WB_1;
// UDP_ff_5p5v_5p5v_m40c_PIOHO_50_50_UDP_0( MGM_WB_0, EN, PULL_ON, I, PULL_UP_DOWN );
// wire EN_inv_for_PIOH_50_50;
// not MGM_BG_1( EN_inv_for_PIOH_50_50, EN );
// wire PULL_ON_inv_for_PIOH_50_50;
// not MGM_BG_2( PULL_ON_inv_for_PIOH_50_50, PULL_ON );
// and MGM_BG_3( MGM_WB_1, EN_inv_for_PIOH_50_50, PULL_ON_inv_for_PIOH_50_50 );
// bufif0 MGM_BG_4( PAD, MGM_WB_0,MGM_WB_1 );
   bufif1 (weak0,weak1) (PAD, PULL_UP_DOWN, PULL_ON) ;
   bufif1 (PAD, I, EN) ;


endmodule
`endcelldefine



`celldefine
module POK_50_50_func( VDDO_OK, VDD_OK );
   output VDDO_OK, VDD_OK;
   assign VDDO_OK = 1'b1;
   assign VDD_OK = 1'b1;


endmodule
`endcelldefine



`celldefine
module PV0A_50_50_func( VSSO );
   output VSSO;
   assign VSSO = 1'b0;


endmodule
`endcelldefine



`celldefine
module PV0C_50_50_50_func( VSSC, VDDC );
   output VDDC, VSSC;
   assign VDDC = 1'b1;
   assign VSSC = 1'b0;


endmodule
`endcelldefine



`celldefine
module PV0F_50_50_func( VSSO );
   output VSSO;
   assign VSSO = 1'b0;


endmodule
`endcelldefine



`celldefine
module PV0I_50_50_func( VSS );
   output VSS;
   assign VSS = 1'b0;


endmodule
`endcelldefine



`celldefine
module PVDA_50_NA_func( VDDO );
   output VDDO;
   assign VDDO = 1'b1;


endmodule
`endcelldefine



`celldefine
module PVDC_NA_NA_50_func( VDDC, VSSC );
   output VDDC, VSSC;
   assign VDDC = 1'b1;
   assign VSSC = 1'b0;


endmodule
`endcelldefine



`celldefine
module PVDF_50_50_func( VDDO );
   output VDDO;
   assign VDDO = 1'b1;


endmodule
`endcelldefine



`celldefine
module PVDI_NA_50_func( VDD );
   output VDD;
   assign VDD = 1'b1;


endmodule
`endcelldefine



`celldefine
module PVPP_50_NA_func( PAD, PADR );
   output PAD, PADR;
   assign PAD = 1'b1;
   assign PADR = 1'b1;


endmodule
`endcelldefine
